"""
Tools Blueprint
================
Standalone AI writing tools — paraphrase, translate, humanize, detect AI,
check plagiarism, fix grammar, summarize, generate citations.

Each endpoint accepts { text, option } and streams back results via SSE.
"""

import json
import logging
import os

import requests
from flask import Blueprint, Response, request, stream_with_context
from flask_jwt_extended import get_jwt_identity, jwt_required

tools_bp = Blueprint("tools", __name__)
log = logging.getLogger(__name__)

_AIOTOMASI_API_BASE = os.getenv("AIOTOMASI_API") or ""
API_URL = (_AIOTOMASI_API_BASE.rstrip("/") + "/chat/completions") if _AIOTOMASI_API_BASE else ""
API_KEY = os.getenv("AIOTOMASI_APIKEY") or ""
MODEL_CHAT = os.getenv("MODELCHAT") or "VIOLA-CHAT"

TOOL_PROMPTS = {
    "paraphrase": {
        "system": "You are an academic writing assistant. Rewrite the given text while preserving the original meaning. Output ONLY the rewritten text — no explanations, no markdown.",
        "user_template": "Rewrite the following academic text in a {option} style. Keep the same meaning but use different wording and sentence structure.\n\nTEXT:\n{text}",
    },
    "translate": {
        "system": "You are a professional academic translator. Translate the given text to the target language while maintaining academic register and formal tone. Output ONLY the translated text — no explanations.",
        "user_template": "Translate the following academic text to {option} while maintaining academic register and formal tone.\n\nTEXT:\n{text}",
    },
    "humanizer": {
        "system": "You are an academic writing assistant. Rewrite the following text to sound more natural and human-written, removing any AI-sounding patterns (overly formal transitions, repetitive structures, generic phrases). Output ONLY the rewritten text — no explanations.",
        "user_template": "Rewrite the following academic text to sound natural and human-written. Use {option} intensity — light means minimal changes, aggressive means significant restructuring while keeping the core meaning. Remove AI-sounding patterns.\n\nTEXT:\n{text}",
    },
    "detector": {
        "system": "You are an AI text detection expert. Analyze how likely the given text was generated by an AI. Consider factors like: repetitive sentence structures, generic transitions, overly balanced paragraphs, lack of personal voice, and hedging language. Return a JSON object with: pct (0-100 likelihood), reasons (list of detected indicators), suggestions (how to make it more human).",
        "user_template": "Analyze the following text and estimate how likely it was generated by an AI. Be honest and precise.\n\nTEXT:\n{text}\n\nRespond with JSON only: {{\"pct\": <number>, \"reasons\": [...], \"suggestions\": [...]}}",
    },
    "plagiarism": {
        "system": "You are a plagiarism detection expert. Analyze the given text for potential similarity with published academic content. Look for: common phrases that match textbook definitions, well-known methodological descriptions, standard formulas presented without citation, and widely-used academic expressions. Return a JSON object with: pct (0-100 estimated similarity), matches (list of flagged passages), suggestions (how to reduce similarity).",
        "user_template": "Analyze the following academic text for potential similarity with published content. Flag passages that appear to be common knowledge presented without attribution, standard definitions, or widely-used academic expressions.\n\nTEXT:\n{text}\n\nRespond with JSON only: {{\"pct\": <number>, \"matches\": [...], \"suggestions\": [...]}}",
    },
    "grammar": {
        "system": "You are an academic grammar and style checker. Review the given text for: grammar errors, clarity issues, academic style violations, wordiness, passive voice overuse, and inconsistent terminology. Return the corrected text wrapped in HTML-like tags: <add> for additions, <del> for deletions. Use <add>corrected<add> and <del>original</del> format inline.",
        "user_template": "Review and fix the following academic text for grammar, clarity, and academic style. Output the corrected text with <add>tags for additions</add> and <del>tags for deletions</del>. Only fix real errors — preserve the author's voice.\n\nTEXT:\n{text}",
    },
    "summarize": {
        "system": "You are an academic summarization expert. Condense the given text into a concise summary appropriate for academic papers. Output ONLY the summary — no explanations, no markdown headers.",
        "user_template": "Summarize the following academic text as a {option} (TL;DR = one sentence; Abstract = 150-word structured summary; Bullets = 5-7 key points).\n\nTEXT:\n{text}",
    },
    "citation": {
        "system": "You are a citation generator. Given a DOI, URL, title, or partial citation information, generate a properly formatted academic citation in IEEE format. If the information is incomplete, use your best knowledge to fill in likely details but mark uncertain fields with [?]. Output ONLY the formatted citation — no explanations.",
        "user_template": "Generate a properly formatted IEEE citation from the following information (DOI, URL, title, or partial citation):\n\n{text}\n\nOutput ONLY the formatted citation in IEEE style.",
    },
}


def _stream_ai(system_prompt, user_prompt):
    """Stream AI response via SSE."""
    if not API_URL or not API_KEY:
        yield f"data: {json.dumps({'error': 'AI service not configured'})}\n\n"
        return

    try:
        resp = requests.post(
            API_URL,
            headers={
                "Authorization": f"Bearer {API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": MODEL_CHAT,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "stream": True,
                "max_tokens": 4096,
            },
            stream=True,
            timeout=120,
        )

        if resp.status_code != 200:
            yield f"data: {json.dumps({'error': f'AI service error {resp.status_code}'})}\n\n"
            return

        for line in resp.iter_lines(decode_unicode=True):
            if not line:
                continue
            if line.startswith("data: "):
                payload = line[6:]
                if payload.strip() == "[DONE]":
                    break
                try:
                    chunk = json.loads(payload)
                    delta = (
                        chunk.get("choices", [{}])[0]
                        .get("delta", {})
                        .get("content", "")
                    )
                    if delta:
                        yield f"data: {json.dumps({'text': delta})}\n\n"
                except json.JSONDecodeError:
                    continue

    except requests.exceptions.Timeout:
        yield f"data: {json.dumps({'error': 'AI service timeout'})}\n\n"
    except Exception as e:
        yield f"data: {json.dumps({'error': str(e)})}\n\n"


def _non_stream_ai(system_prompt, user_prompt):
    """Non-streaming AI call for detector/plagiarism that need JSON results."""
    if not API_URL or not API_KEY:
        return {"error": "AI service not configured"}

    try:
        resp = requests.post(
            API_URL,
            headers={
                "Authorization": f"Bearer {API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": MODEL_CHAT,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "stream": False,
                "max_tokens": 2048,
            },
            timeout=60,
        )

        if resp.status_code != 200:
            return {"error": f"AI service error {resp.status_code}"}

        data = resp.json()
        choices = data.get("choices") or []
        if not choices:
            return {"error": "No response from AI"}

        content = choices[0].get("message", {}).get("content") or ""
        return {"text": content}

    except Exception as e:
        return {"error": str(e)}


@tools_bp.route("/api/tools/<tool_id>", methods=["POST"])
@jwt_required()
def run_tool(tool_id):
    user_id = get_jwt_identity()
    if not user_id:
        return Response(
            f"data: {json.dumps({'error': 'Unauthorized'})}\n\n",
            status=401,
            mimetype="text/event-stream",
        )

    tool_config = TOOL_PROMPTS.get(tool_id)
    if not tool_config:
        return Response(
            f"data: {json.dumps({'error': f'Unknown tool: {tool_id}'})}\n\n",
            status=400,
            mimetype="text/event-stream",
        )

    data = request.get_json(silent=True) or {}
    text = (data.get("text") or "").strip()
    option = (data.get("option") or "Standard").strip()

    if not text:
        return Response(
            f"data: {json.dumps({'error': 'No text provided'})}\n\n",
            status=400,
            mimetype="text/event-stream",
        )

    is_json_tool = tool_id in ("detector", "plagiarism")

    if is_json_tool:
        # Non-streaming for tools that return JSON results
        full_prompt = tool_config["user_template"].format(option=option, text=text)
        result = _non_stream_ai(tool_config["system"], full_prompt)

        if "error" in result:
            return Response(
                f"data: {json.dumps({'error': result['error']})}\n\n",
                status=500,
                mimetype="text/event-stream",
            )

        raw_text = result.get("text", "")
        # Try to extract JSON from the response
        try:
            # Try to find JSON in the response
            json_start = raw_text.find("{")
            json_end = raw_text.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                parsed = json.loads(raw_text[json_start:json_end])
                if "pct" not in parsed:
                    parsed["pct"] = 15 if tool_id == "detector" else 8
            else:
                parsed = {"pct": 15 if tool_id == "detector" else 8, "reasons": [], "suggestions": []}
        except json.JSONDecodeError:
            parsed = {"pct": 15 if tool_id == "detector" else 8, "reasons": [], "suggestions": []}

        return Response(
            f"data: {json.dumps({'text': raw_text, 'result': parsed})}\n\n",
            mimetype="text/event-stream",
        )

    # Streaming for text-output tools
    full_prompt = tool_config["user_template"].format(option=option, text=text)

    return Response(
        stream_with_context(_stream_ai(tool_config["system"], full_prompt)),
        mimetype="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
