"""
AEJgen.py - Generator DOCX untuk jurnal AEJ.
Menggunakan dokumen asli AEJ.docx sebagai base template.
Data diambil dari _template.json.
Auto-generated by gen_factory.py.
"""
import json
import copy
import shutil
import re
import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, Cm, Inches, Twips, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml, OxmlElement
from lxml import etree

BASE = Path(__file__).resolve().parent
TEMPLATE_DOCX = BASE / "AEJ.docx"
TEMPLATE_JSON = BASE / "_template.json"
OUTPUT_DOCX = BASE / "AEJ_output.docx"

CFG = {
    "font_body": "Calibri",
    "font_title": "Calibri",
    "font_heading": "Calibri",
    "size_body": 9,
    "size_title": 14,
    "size_heading1": 11,
    "size_heading2": 10,
    "size_caption": 8,
    "heading_color": (0x94, 0x36, 0x34),
    "size_reference": 8,
    "columns": 2,
    "first_line_indent_tw": 182,
    "table_borders": "full",
    "fig_prefix": "Fig.",
    "tbl_prefix": "Table",
    "section_heading_upper": True,
}

def _format_reference(item) -> str:
    """Format a reference dict into a citation string."""
    if isinstance(item, str):
        return item.strip()
    if not isinstance(item, dict):
        return str(item).strip()
    text = item.get("text") or item.get("Text") or item.get("value")
    if text:
        return str(text).strip()
    parts = []
    authors = item.get("authors", [])
    if authors:
        parts.append(", ".join(str(a) for a in authors) if isinstance(authors, list) else str(authors))
    year = item.get("year")
    if year:
        parts.append(f"({year})")
    title = item.get("title", "")
    if title:
        parts.append(f'"{title},"')
    jname = item.get("journal") or item.get("conference") or ""
    if jname:
        parts.append(str(jname) + ",")
    vol = item.get("volume", "")
    if vol:
        parts.append(f"vol. {vol},")
    issue = item.get("issue", "")
    if issue:
        parts.append(f"no. {issue},")
    pages = item.get("pages", "")
    if pages:
        parts.append(f"pp. {pages},")
    doi = item.get("doi", "")
    if doi:
        parts.append(f"doi: {doi}.")
    url = item.get("url", "")
    if url:
        accessed = item.get("accessed", "")
        parts.append(f"[Online]. Available: {url}" + (f" [Accessed: {accessed}]." if accessed else "."))
    publisher = item.get("publisher", "")
    if publisher and not jname:
        location = item.get("location", "")
        parts.append(f"{location}: {publisher}." if location else f"{publisher}.")
    result = " ".join(str(p) for p in parts if p).strip()
    result = result.replace(" , ", ", ").replace(" .", ".")
    if result.endswith(","):
        result = result[:-1] + "."
    if not result.endswith("."):
        result = result + "."
    return result

def load_json():
    with open(TEMPLATE_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def set_run_font(run, font_name=None, size_pt=None, bold=None, italic=None, color=None):
    if font_name:
        run.font.name = font_name
        rPr = run._element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = OxmlElement("w:rFonts")
            rPr.insert(0, rFonts)
        rFonts.set(qn("w:ascii"), font_name)
        rFonts.set(qn("w:hAnsi"), font_name)
        rFonts.set(qn("w:cs"), font_name)
    if size_pt:
        run.font.size = Pt(size_pt)
    if bold is not None:
        run.bold = bold
    if italic is not None:
        run.italic = italic
    if color:
        run.font.color.rgb = RGBColor(*color)


def set_para_spacing(para, before_pt=None, after_pt=None, line_tw=None):
    pf = para.paragraph_format
    if before_pt is not None:
        pf.space_before = Pt(before_pt)
    if after_pt is not None:
        pf.space_after = Pt(after_pt)
    if line_tw is not None:
        pPr = para._element.get_or_add_pPr()
        spacing = pPr.find(qn("w:spacing"))
        if spacing is None:
            spacing = OxmlElement("w:spacing")
            pPr.append(spacing)
        spacing.set(qn("w:line"), str(line_tw))
        spacing.set(qn("w:lineRule"), "auto")


def set_para_indent(para, first_line_tw=None, left_tw=None, hanging_tw=None):
    pPr = para._element.get_or_add_pPr()
    ind = pPr.find(qn("w:ind"))
    if ind is None:
        ind = OxmlElement("w:ind")
        pPr.append(ind)
    if first_line_tw is not None:
        ind.set(qn("w:firstLine"), str(first_line_tw))
    if left_tw is not None:
        ind.set(qn("w:left"), str(left_tw))
    if hanging_tw is not None:
        ind.set(qn("w:hanging"), str(hanging_tw))
        if ind.get(qn("w:firstLine")):
            del ind.attrib[qn("w:firstLine")]

def _detect_table_borders(doc):
    """Scan template for first body table and extract its border style.
    Returns a dict of {side: {val, sz, color}} compatible with set_table_borders."""
    body = doc._element.body
    body_tbl_found = False
    for child in body:
        if child.tag == qn("w:tbl"):
            # Skip first table (masthead) — no borders
            if not body_tbl_found:
                body_tbl_found = True
                continue
            # Second table = body table
            tblPr = child.find(qn("w:tblPr"))
            if tblPr is None:
                return None
            borders_elem = tblPr.find(qn("w:tblBorders"))
            if borders_elem is None:
                return None
            
            result = {}
            for side in ["top", "left", "bottom", "right", "insideH", "insideV"]:
                border = borders_elem.find(qn(f"w:{side}"))
                if border is not None:
                    result[side] = {
                        "val": border.get(qn("w:val"), "none"),
                        "sz": border.get(qn("w:sz"), "0"),
                        "color": border.get(qn("w:color"), "auto"),
                    }
                else:
                    result[side] = None  # Not set = inherit (none)
            
            # Also check cell-level borders on first row
            first_row = child.find(qn("w:tr"))
            if first_row is not None:
                first_cell = first_row.find(qn("w:tc"))
                if first_cell is not None:
                    tcPr = first_cell.find(qn("w:tcPr"))
                    if tcPr is not None:
                        cell_borders = tcPr.find(qn("w:tcBorders"))
                        if cell_borders is not None:
                            result["_cell"] = {}
                            for side in ["top", "left", "bottom", "right"]:
                                cb = cell_borders.find(qn(f"w:{side}"))
                                if cb is not None:
                                    result["_cell"][side] = {
                                        "val": cb.get(qn("w:val"), "none"),
                                        "sz": cb.get(qn("w:sz"), "0"),
                                    }
            return result
    return None


def set_table_borders(table, style_borders):
    """Apply border style to a table. style_borders can be:
    - dict: direct border definition from _detect_table_borders
    - str: legacy keyword ("full", "horizontal", "partial", "none")
    """
    from docx.oxml import OxmlElement
    tblPr = table._tbl.find(qn("w:tblPr"))
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        table._tbl.insert(0, tblPr)
    # Remove existing borders
    existing = tblPr.find(qn("w:tblBorders"))
    if existing is not None:
        tblPr.remove(existing)
    
    if isinstance(style_borders, dict):
        borders = OxmlElement("w:tblBorders")
        sides = ["top", "left", "bottom", "right", "insideH", "insideV"]
        for side in sides:
            el = OxmlElement(f"w:{side}")
            if side in style_borders and style_borders[side] is not None:
                b = style_borders[side]
                el.set(qn("w:val"), str(b.get("val", "none")))
                el.set(qn("w:sz"), str(b.get("sz", "0")))
                el.set(qn("w:space"), "0")
                el.set(qn("w:color"), str(b.get("color", "auto")))
            else:
                el.set(qn("w:val"), "none")
                el.set(qn("w:sz"), "0")
                el.set(qn("w:space"), "0")
                el.set(qn("w:color"), "auto")
            borders.append(el)
        tblPr.append(borders)
    elif isinstance(style_borders, str):
        style = style_borders
        borders = OxmlElement("w:tblBorders")
        for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
            el = OxmlElement(f"w:{side}")
            if style == "horizontal":
                if side in ("top", "bottom", "insideH"):
                    el.set(qn("w:val"), "single")
                    el.set(qn("w:sz"), "4")
                    el.set(qn("w:space"), "0")
                    el.set(qn("w:color"), "000000")
                else:
                    el.set(qn("w:val"), "none")
                    el.set(qn("w:sz"), "0")
                    el.set(qn("w:space"), "0")
                    el.set(qn("w:color"), "auto")
            elif style == "full":
                el.set(qn("w:val"), "single")
                el.set(qn("w:sz"), "4")
                el.set(qn("w:space"), "0")
                el.set(qn("w:color"), "000000")
            elif style == "partial":
                if side in ("insideV", "left", "right"):
                    el.set(qn("w:val"), "none")
                    el.set(qn("w:sz"), "0")
                    el.set(qn("w:space"), "0")
                    el.set(qn("w:color"), "auto")
                else:
                    el.set(qn("w:val"), "single")
                    el.set(qn("w:sz"), "4")
                    el.set(qn("w:space"), "0")
                    el.set(qn("w:color"), "auto")
            else:  # none
                el.set(qn("w:val"), "none")
                el.set(qn("w:sz"), "0")
                el.set(qn("w:space"), "0")
                el.set(qn("w:color"), "auto")
            borders.append(el)
        tblPr.append(borders)
    
    # Apply cell-level borders if detected
    if isinstance(style_borders, dict) and "_cell" in style_borders:
        cell_cfg = style_borders["_cell"]
        for row in table.rows:
            for cell in row.cells:
                tcPr = cell._tc.find(qn("w:tcPr"))
                if tcPr is None:
                    tcPr = OxmlElement("w:tcPr")
                    cell._tc.insert(0, tcPr)
                existing_cb = tcPr.find(qn("w:tcBorders"))
                if existing_cb is not None:
                    tcPr.remove(existing_cb)
                if any(cell_cfg.get(s) for s in ["top", "bottom", "left", "right"]):
                    cell_borders = OxmlElement("w:tcBorders")
                    for side in ["top", "bottom", "left", "right"]:
                        el = OxmlElement(f"w:{side}")
                        if side in cell_cfg and cell_cfg[side] is not None:
                            cb = cell_cfg[side]
                            el.set(qn("w:val"), str(cb.get("val", "none")))
                            el.set(qn("w:sz"), str(cb.get("sz", "0")))
                            el.set(qn("w:space"), "0")
                            el.set(qn("w:color"), "auto")
                        else:
                            el.set(qn("w:val"), "none")
                            el.set(qn("w:sz"), "0")
                            el.set(qn("w:space"), "0")
                            el.set(qn("w:color"), "auto")
                        cell_borders.append(el)
                    tcPr.append(cell_borders)
    tblPr.append(borders)


def clear_body(doc):
    """Clear body text/tables but keep section break paragraphs and top image paragraphs/tables (logos)."""
    body = doc._element.body
    sectpr_paras = []
    logo_paras = []
    logo_tables = []

    # First pass: identify logo paragraphs (images in first 3 paragraphs)
    para_count = 0
    for child in body:
        if child.tag == qn("w:p"):
            para_count += 1
            if para_count <= 3:
                # Check if paragraph has image/drawing
                has_image = False
                for run in child.findall(qn("w:r")):
                    if run.findall(qn("w:drawing")):
                        has_image = True
                        break
                if has_image:
                    logo_paras.append(child)

    # Identify logo tables (tables with drawings in first 3 tables)
    table_count = 0
    for child in body:
        if child.tag == qn("w:tbl"):
            table_count += 1
            if table_count <= 3:
                # Check if table has drawing
                has_drawing = len(child.findall(f".//{qn('w:drawing')}")) > 0
                if has_drawing:
                    logo_tables.append(child)

    # Second pass: clear body but preserve logos and section breaks
    for child in list(body):
        if child.tag == qn("w:sectPr"):
            continue
        if child in logo_paras:
            continue  # Preserve logo paragraphs
        if child in logo_tables:
            continue  # Preserve logo tables
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                # Keep this paragraph (it has section break)
                # But clear its text content
                for run in child.findall(qn("w:r")):
                    child.remove(run)
                sectpr_paras.append(child)
                continue
        body.remove(child)
    return sectpr_paras


def distribute_section_breaks(doc, n_breaks):
    """Insert n_breaks section breaks evenly distributed among body paragraphs."""
    if n_breaks <= 0:
        return
    body = doc._element.body
    # Count content paragraphs (exclude final sectPr)
    content_elements = [c for c in body if c.tag != qn("w:sectPr")]
    total = len(content_elements)
    if total == 0:
        return
    # Calculate interval
    interval = max(1, total // (n_breaks + 1))
    # Insert section breaks at intervals (from end to start to preserve indices)
    insert_positions = []
    for i in range(1, n_breaks + 1):
        pos = min(i * interval, total - 1)
        if pos not in insert_positions:
            insert_positions.append(pos)
    # Get final sectPr to copy its properties
    final_sectpr = body.find(qn("w:sectPr"))
    for pos in reversed(insert_positions):
        target = content_elements[pos] if pos < len(content_elements) else content_elements[-1]
        # Add sectPr to this paragraph's pPr (inline section break)
        if target.tag == qn("w:p"):
            pPr = target.find(qn("w:pPr"))
            if pPr is None:
                pPr = OxmlElement("w:pPr")
                target.insert(0, pPr)
            sp = OxmlElement("w:sectPr")
            # Copy page size and margins from final sectPr
            if final_sectpr is not None:
                for prop_tag in ("w:pgSz", "w:pgMar", "w:cols"):
                    orig = final_sectpr.find(qn(prop_tag))
                    if orig is not None:
                        import copy
                        sp.append(copy.deepcopy(orig))
            pPr.append(sp)


def insert_column_break(doc, num_cols):
    """Insert continuous section break inline (attach to last paragraph, not empty para)."""
    if CFG["columns"] <= 1:
        return
    body = doc._element.body
    final_sectpr = body.find(qn("w:sectPr"))

    # Find last content paragraph (not empty, not already has sectPr)
    last_para = None
    for child in reversed(list(body)):
        if child.tag == qn("w:sectPr"):
            continue
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                continue
            last_para = child
            break

    if last_para is None:
        # No content paragraph found, skip
        return

    # Attach sectPr inline to last paragraph
    pPr = last_para.find(qn("w:pPr"))
    if pPr is None:
        pPr = OxmlElement("w:pPr")
        last_para.insert(0, pPr)

    sp = OxmlElement("w:sectPr")
    # Set type=continuous
    sec_type = OxmlElement("w:type")
    sec_type.set(qn("w:val"), "continuous")
    sp.append(sec_type)
    # Copy page size and margins from final sectPr
    if final_sectpr is not None:
        for prop_tag in ("w:pgSz", "w:pgMar"):
            orig = final_sectpr.find(qn(prop_tag))
            if orig is not None:
                import copy
                sp.append(copy.deepcopy(orig))
    # Set columns
    cols_el = OxmlElement("w:cols")
    cols_el.set(qn("w:num"), str(num_cols))
    sp.append(cols_el)
    pPr.append(sp)
def remove_trailing_empty_sectpr_paras(doc):
    """Remove empty paragraphs with sectPr at the end of body by moving sectPr to previous content paragraph."""
    body = doc._element.body
    to_process = []

    # Scan backwards from end to find trailing empty sectPr paragraphs
    for child in reversed(list(body)):
        if child.tag == qn("w:sectPr"):
            # Skip final sectPr, continue scanning
            continue
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                # This paragraph has a section break
                # Check if it's empty (no runs with text)
                has_content = False
                for run in child.findall(qn("w:r")):
                    t_elem = run.find(qn("w:t"))
                    if t_elem is not None and t_elem.text and t_elem.text.strip():
                        has_content = True
                        break

                if not has_content:
                    # Empty paragraph with sectPr - mark for processing
                    to_process.append(child)
                else:
                    # Non-empty paragraph - stop scanning
                    break
            else:
                # Paragraph without sectPr - stop scanning
                break
        elif child.tag == qn("w:tbl"):
            # Table - stop scanning (content found)
            break

    # Process each trailing empty sectPr paragraph
    removed_count = 0
    for empty_para in to_process:
        # Extract the sectPr from this empty paragraph
        pPr = empty_para.find(qn("w:pPr"))
        sectPr = pPr.find(qn("w:sectPr")) if pPr is not None else None

        if sectPr is not None:
            # Find the last content paragraph before this empty one
            empty_index = list(body).index(empty_para)
            target_para = None

            for i in range(empty_index - 1, -1, -1):
                child = list(body)[i]
                if child.tag == qn("w:p"):
                    # Check if this paragraph has content or is also empty
                    has_content = False
                    for run in child.findall(qn("w:r")):
                        t_elem = run.find(qn("w:t"))
                        if t_elem is not None and t_elem.text and t_elem.text.strip():
                            has_content = True
                            break
                    if has_content:
                        target_para = child
                        break
                elif child.tag == qn("w:tbl"):
                    # Can't attach sectPr to table, skip this one
                    break

            if target_para is not None:
                # Move sectPr to target paragraph
                target_pPr = target_para.find(qn("w:pPr"))
                if target_pPr is None:
                    target_pPr = OxmlElement("w:pPr")
                    target_para.insert(0, target_pPr)

                # Remove sectPr from empty paragraph and add to target
                pPr.remove(sectPr)
                target_pPr.append(sectPr)

                # Now remove the empty paragraph
                body.remove(empty_para)
                removed_count += 1

    return removed_count


def _remove_trailing_empty_sectpr_paras(doc):
    """Hapus paragraf kosong bersectPr (incl. zero-width) di ekor body."""
    body = doc._element.body
    to_remove = []
    for child in reversed(list(body)):
        if child.tag == qn("w:sectPr"):
            continue
        if child.tag != qn("w:p"):
            break
        pPr = child.find(qn("w:pPr"))
        if pPr is None or pPr.find(qn("w:sectPr")) is None:
            break
        txt = "".join(t.text or "" for t in child.findall(f".//{qn('w:t')}")).strip()
        if not txt or all(c == '\u200B' for c in txt):
            to_remove.append(child)
        else:
            break
    for child in to_remove:
        body.remove(child)


def _remove_trailing_empty_paras(doc):
    """Remove ALL trailing empty paragraphs (with or without sectPr) from body."""
    body = doc._element.body
    to_remove = []
    for child in reversed(list(body)):
        if child.tag == qn("w:sectPr"):
            continue  # Skip final sectPr
        if child.tag != qn("w:p"):
            break  # Table or other content - stop
        # Check if paragraph has any text content
        txt = "".join(t.text or "" for t in child.findall(f".//{qn('w:t')}")).strip()
        if not txt or all(c == '\u200B' for c in txt):
            to_remove.append(child)
        else:
            break  # Non-empty paragraph - stop
    for child in to_remove:
        body.remove(child)


def add_title(doc, data):
    title = str(data.get("title", "Paper Title")).strip()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p, before_pt=0, after_pt=6)
    run = p.add_run(title)
    set_run_font(run, CFG["font_title"], CFG["size_title"], bold=True)


def add_authors(doc, data):
    authors = data.get("authors", [])
    if not authors:
        return
    # Author names
    names = [a["name"] if isinstance(a, dict) else str(a) for a in authors]
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p, before_pt=6, after_pt=3)
    run = p.add_run(", ".join(names))
    set_run_font(run, CFG["font_title"], CFG["size_body"])

    # Affiliations
    affiliations = set()
    for a in authors:
        if isinstance(a, dict) and a.get("affiliation"):
            affiliations.add(a["affiliation"])
    if affiliations:
        p2 = doc.add_paragraph()
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p2, before_pt=0, after_pt=3)
        run2 = p2.add_run("; ".join(affiliations))
        set_run_font(run2, CFG["font_title"], CFG["size_body"] - 1, italic=True)

    # Emails
    emails = [a.get("email", "") for a in authors if isinstance(a, dict) and a.get("email")]
    if emails:
        p3 = doc.add_paragraph()
        p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p3, before_pt=0, after_pt=6)
        run3 = p3.add_run(", ".join(emails))
        set_run_font(run3, CFG["font_title"], CFG["size_body"] - 1, italic=True)


def add_abstract(doc, data):
    abstract = _clean_latex(str(data.get("abstract", "")).strip())
    if not abstract:
        return
    # Label
    p_label = doc.add_paragraph()
    p_label.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_label, before_pt=6, after_pt=3)
    run_label = p_label.add_run("Abstract")
    set_run_font(run_label, CFG["font_body"], CFG["size_body"], bold=True)
    # Content
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=6)
    run = p.add_run(abstract)
    set_run_font(run, CFG["font_body"], CFG["size_body"], italic=True)


def add_keywords(doc, data):
    keywords = data.get("keywords", [])
    if not keywords:
        return
    if isinstance(keywords, list):
        kw_text = ", ".join(str(k) for k in keywords)
    else:
        kw_text = str(keywords)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=6)
    run_label = p.add_run("Keywords: ")
    set_run_font(run_label, CFG["font_body"], CFG["size_body"], bold=True)
    run_kw = p.add_run(kw_text)
    set_run_font(run_kw, CFG["font_body"], CFG["size_body"], italic=True)


def add_section_heading(doc, title):
    """Add section heading - NO manual numbering (let Word handle it)."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
    display = title.upper() if CFG["section_heading_upper"] else title
    run = p.add_run(display)
    set_run_font(run, CFG["font_heading"], CFG["size_heading1"], bold=True, color=CFG["heading_color"])


def add_subsection_heading(doc, title):
    """Add subsection heading - NO manual numbering."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
    run = p.add_run(title)
    set_run_font(run, CFG["font_heading"], CFG["size_heading2"], bold=True)



def _inject_masthead_content(doc, data):
    """Inject title, author, and abstract into masthead table cells.
    Replaces placeholder text (TITLE OF THE ARTICLE, A GOOD ABSTRACT, example authors)
    with actual paper data.
    """
    from lxml import etree
    from docx.oxml.ns import qn as qn2
    body = doc._element.body

    # Find masthead table — first table with drawings (branding)
    masthead_table = None
    for child in body:
        if child.tag == qn("w:tbl") and child.findall(f".//{qn('w:drawing')}"):
            masthead_table = child
            break
    if masthead_table is None:
        return

    rows = masthead_table.findall(qn("w:tr"))
    if len(rows) < 7:
        return

    title = _clean_latex(str(data.get("title", "")).strip())
    abstract = _clean_latex(str(data.get("abstract", "")).strip())
    authors_data = data.get("authors", [])
    if isinstance(authors_data, list) and authors_data:
        author_str = ", ".join(str(a.get("name", a)) if isinstance(a, dict) else str(a) for a in authors_data)
    else:
        author_str = ""
    # Find institution from various possible keys
    institution = str(data.get("institution", "")).strip()
    if not institution and isinstance(authors_data, list) and authors_data and isinstance(authors_data[0], dict):
        first_author = authors_data[0]
        institution = str(first_author.get("affiliation", first_author.get("institute", ""))).strip()
    email = str(data.get("email", "")).strip()
    if not email and isinstance(authors_data, list) and authors_data and isinstance(authors_data[0], dict):
        email = str(authors_data[0].get("email", "")).strip()
    if isinstance(data.get("keywords"), list):
        kw_str = _clean_latex(", ".join(data["keywords"]))
    else:
        kw_str = _clean_latex(str(data.get("keywords", "")))

    # Row 3 Cell 0: TITLE + AUTHORS — clear all, inject full title+author
    row3 = rows[3]
    tc = row3.findall(qn("w:tc"))
    if tc:
        cell = tc[0]
        # Inject title in first paragraph — title in Run1, author+affiliation in Run2+
        all_ps = cell.findall(qn("w:p"))
        if all_ps:
            p = all_ps[0]
            all_runs = p.findall(qn("w:r"))
            
            # Clear all runs in first paragraph
            for r in all_runs:
                for t in r.findall(f".//{qn('w:t')}"):
                    t.text = ""
                    t.set(qn("xml:space"), "preserve")
            
            # Run0: title
            r0 = all_runs[0] if all_runs else etree.SubElement(p, qn("w:r"))
            t0 = r0.find(qn("w:t"))
            if t0 is not None and title:
                t0.text = title
                t0.set(qn("xml:space"), "preserve")
            
            # p[1]: author
            if len(all_ps) > 1 and author_str:
                p2 = all_ps[1]
                p2_runs = p2.findall(qn("w:r"))
                for r in p2_runs:
                    for t in r.findall(f".//{qn('w:t')}"):
                        t.text = ""
                        t.set(qn("xml:space"), "preserve")
                r_auth = p2_runs[0] if p2_runs else etree.SubElement(p2, qn("w:r"))
                t_auth = r_auth.find(qn("w:t"))
                if t_auth is None:
                    t_auth = etree.SubElement(r_auth, qn("w:t"))
                t_auth.text = author_str
                t_auth.set(qn("xml:space"), "preserve")
            
            # p[2]: institution
            if len(all_ps) > 2 and institution:
                p3 = all_ps[2]
                p3_runs = p3.findall(qn("w:r"))
                for r in p3_runs:
                    for t in r.findall(f".//{qn('w:t')}"):
                        t.text = ""
                        t.set(qn("xml:space"), "preserve")
                r_inst = p3_runs[0] if p3_runs else etree.SubElement(p3, qn("w:r"))
                t_inst = r_inst.find(qn("w:t"))
                if t_inst is None:
                    t_inst = etree.SubElement(r_inst, qn("w:t"))
                t_inst.text = institution
                t_inst.set(qn("xml:space"), "preserve")
            
            # p[3]: email
            if len(all_ps) > 3 and email:
                p4 = all_ps[3]
                p4_runs = p4.findall(qn("w:r"))
                for r in p4_runs:
                    for t in r.findall(f".//{qn('w:t')}"):
                        t.text = ""
                        t.set(qn("xml:space"), "preserve")
                r_em = p4_runs[0] if p4_runs else etree.SubElement(p4, qn("w:r"))
                t_em = r_em.find(qn("w:t"))
                if t_em is None:
                    t_em = etree.SubElement(r_em, qn("w:t"))
                t_em.text = email
                t_em.set(qn("xml:space"), "preserve")
            
            # Clear remaining paragraphs (p[4+])
            for pi in range(4, len(all_ps)):
                p_rem = all_ps[pi]
                body = doc._element.body
                # Remove paragraph from parent
                parent = p_rem.getparent()
                if parent is not None:
                    parent.remove(p_rem)
                else:
                    for t in p_rem.findall(f".//{qn('w:t')}"):
                        t.text = ""
                        t.set(qn("xml:space"), "preserve")

    # Row 5 Cell 1: ABSTRACT — clear ALL content, inject full abstract
    if len(rows) > 5:
        row5 = rows[5]
        tc = row5.findall(qn("w:tc"))
        if len(tc) > 1:
            cell = tc[1]
            # Clear all existing paragraph text runs EXCEPT p[0] (Abstract heading)
            for idx, p in enumerate(cell.findall(qn("w:p"))):
                if idx == 0:
                    continue  # preserve "Abstract" heading
                for t in p.findall(f".//{qn('w:t')}"):
                    t.text = ""
                    t.set(qn("xml:space"), "preserve")
            # Inject abstract into p[2] (content paragraph after heading)
            all_cell_ps = cell.findall(qn("w:p"))
            if len(all_cell_ps) >= 3 and abstract:
                p_content = all_cell_ps[2]
                first_run = p_content.find(qn("w:r"))
                if first_run is None:
                    from lxml import etree
                    first_run = etree.SubElement(p_content, qn("w:r"))
                first_t = first_run.find(qn("w:t"))
                if first_t is not None:
                    first_t.text = abstract
                    first_t.set(qn("xml:space"), "preserve")
            
            # Inject keywords in the keywords paragraph (p[4] typically)
            if kw_str:
                all_cell_ps = cell.findall(qn("w:p"))
                if len(all_cell_ps) >= 5:
                    kw_p = all_cell_ps[4]
                    kw_runs = kw_p.findall(qn("w:r"))
                    # Clear existing keyword runs, inject new
                    if len(kw_runs) >= 2:
                        # First run: "Keywords:" (preserve formatting)
                        kw_t0 = kw_runs[0].find(qn("w:t"))
                        if kw_t0 is not None:
                            kw_t0.text = "Keywords"
                            kw_t0.set(qn("xml:space"), "preserve")
                        # Second run: actual keywords (clean+inject)
                        kw_t1 = kw_runs[1].find(qn("w:t"))
                        if kw_t1 is not None:
                            kw_t1.text = f": {kw_str}."
                            kw_t1.set(qn("xml:space"), "preserve")
                        # Third run (KEYWORDS REQUIRED): clear
                        if len(kw_runs) > 2:
                            for kw_t_rem in kw_runs[2:]:
                                t = kw_t_rem.find(qn("w:t"))
                                if t is not None:
                                    t.text = ""
                                    t.set(qn("xml:space"), "preserve")


def _clean_latex(text):
    # Repair LLM streaming artifacts (collapsed integrals, bare math, etc.)
    try:
        from _math_omml import sanitize_llm_text_artifacts
        text = sanitize_llm_text_artifacts(text)
    except Exception:
        pass
    """Strip inline LaTeX markers dari body text supaya tidak bocor ke output."""
    text = re.sub(r'\$([^$]+)\$', r'\1', text)
    text = re.sub(r'\\mathrm\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\mathbf\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\text\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\hat\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\vec\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\overline\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\sqrt\{([^}]*)\}', r'sqrt(\1)', text)
    text = re.sub(r'\\frac\{([^}]*)\}\{([^}]*)\}', r'(\1/\2)', text)
    text = re.sub(r'\\left[(\[{]', '(', text)
    text = re.sub(r'\\right[)\]}]', ')', text)
    text = re.sub(r'\\begin\{cases\}', '', text)
    text = re.sub(r'\\end\{cases\}', '', text)
    text = re.sub(r'\\approx', chr(8776), text)
    text = re.sub(r'\\times', chr(215), text)
    text = re.sub(r'\\cdot', chr(183), text)
    text = re.sub(r'\\quad', ' ', text)
    text = re.sub(r'\\qquad', '  ', text)
    text = re.sub(r'\\infty', chr(8734), text)
    text = re.sub(r'\\circ', chr(176), text)
    text = re.sub(r'\\alpha', chr(945), text)
    text = re.sub(r'\\beta', chr(946), text)
    text = re.sub(r'\\gamma', chr(947), text)
    text = re.sub(r'\\theta', chr(952), text)
    text = re.sub(r'\\lambda', chr(955), text)
    text = re.sub(r'\\sigma', chr(963), text)
    text = re.sub(r'\\omega', chr(969), text)
    text = re.sub(r'\\pi', chr(960), text)
    text = re.sub(r'\\mu', chr(956), text)
    text = re.sub(r'\\Delta', chr(916), text)
    text = re.sub(r'\\partial', chr(8706), text)
    text = re.sub(r'\\phi', chr(966), text)
    text = re.sub(r'\\psi', chr(968), text)
    text = re.sub(r'\\rho', chr(961), text)
    text = re.sub(r'\\tau', chr(964), text)
    text = re.sub(r'\\eta', chr(951), text)
    text = re.sub(r'\\zeta', chr(950), text)
    text = re.sub(r'\\xi', chr(958), text)
    text = re.sub(r'\\chi', chr(967), text)
    text = re.sub(r'\\nu', chr(957), text)
    text = re.sub(r'\\epsilon', chr(949), text)
    text = re.sub(r'\\varepsilon', chr(949), text)
    text = re.sub(r'\\delta', chr(948), text)
    text = re.sub(r'\\kappa', chr(954), text)

    # Convert subscripts to Unicode subscript characters
    _sub_map = {
        '0': '₀', '1': '₁', '2': '₂', '3': '₃', '4': '₄',
        '5': '₅', '6': '₆', '7': '₇', '8': '₈', '9': '₉',
        'i': 'ᵢ', 'j': 'ⱼ', 'k': 'ₖ', 'l': 'ₗ', 'm': 'ₘ',
        'n': 'ₙ', 'o': 'ₒ', 'p': 'ₚ', 'r': 'ᵣ', 's': 'ₛ',
        't': 'ₜ', 'x': 'ₓ', 'y': 'ᵧ', 'z': 'z',
        'a': 'ₐ', 'd': 'd', 'e': 'ₑ', 'h': 'ₕ',
    }
    _sup_map = {
        '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴',
        '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹',
        'n': 'ⁿ', 'x': 'ˣ', 'y': 'ʸ',
    }

    def _sub_single(m):
        c = m.group(1)
        return _sub_map.get(c) or c

    def _sup_single(m):
        c = m.group(1)
        return _sup_map.get(c) or c

    def _sub_braced(m):
        s = m.group(1)
        return ''.join(_sub_map.get(c) or c for c in s)

    def _sup_braced(m):
        s = m.group(1)
        return ''.join(_sup_map.get(c) or c for c in s)

    # Braced sub/superscript: _{abc} → ₐᵦc
    text = re.sub(r'_\{([^}]+)\}', _sub_braced, text)
    text = re.sub(r'\^\{([^}]+)\}', _sup_braced, text)
    # Single-char sub/superscript: _i → ᵢ, ^2 → ²
    text = re.sub(r'_([a-zA-Z0-9])', _sub_single, text)
    text = re.sub(r'\^([a-zA-Z0-9])', _sup_single, text)
    text = re.sub(r'\\[a-zA-Z]+', '', text)
    text = re.sub(r'[{}]', '', text)
    # Strip stray single-char artifacts at edges (LLM data noise)
    # Pattern: paired b/i at both edges (LaTeX \b or \i artifact)
    if text.startswith('b') and text.endswith(' b'):
        text = text[1:].rstrip()
        text = text[:-1].rstrip()
    elif text.startswith('i ') and text.endswith(' i'):
        text = text[2:]
        text = text[:-1].rstrip()
    # Math content: strip stray i/b at edges
    _math_chars = set('ᵢⱼₖₗₘₙₒₚᵣₛₜₓᵧ₀₁₂₃₄₅₆₇₈₉ₐₑₕⁿˣʸ⁰¹²³⁴⁵⁶⁷⁸⁹θαπσβγδελμωφψρτηζξχν')
    if any(c in _math_chars for c in text):
        text = re.sub(r'^[ib](?=[A-Z(θαπσβγδελμω])', '', text)
        text = re.sub(r'^[ib]\s+(?=[θαπσβγδελμω])', '', text)
        text = re.sub(r'(?<=\))[ib]$', '', text)
    return text.strip()


def add_body_text(doc, text):
    cleaned = _clean_latex(text)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
    if CFG["first_line_indent_tw"] > 0:
        set_para_indent(p, first_line_tw=CFG["first_line_indent_tw"])
    run = p.add_run(cleaned)
    set_run_font(run, CFG["font_body"], CFG["size_body"])


def add_figure(doc, fig_data, fig_counter):
    fig_no = str(fig_data.get("ImageNumber", fig_counter)).strip()
    title = str(fig_data.get("Title", "")).strip()
    if not title:
        title = str(fig_data.get("caption", f"Figure {fig_no}")).strip()
    prompt_hint = str(fig_data.get("Prompt", "")).strip()
    image_path = fig_data.get("Path") or fig_data.get("path") or ""
    if not title or title.strip().lower() in {f"figure {fig_no}".lower(), f"fig. {fig_no}".lower()}:
        # ponytail: JSON sometimes has image paths but empty captions; use filename as minimal non-bold caption description.
        # Upgrade path: require captions in frontend upload metadata.
        base = os.path.splitext(os.path.basename(str(image_path)))[0].replace("_", " ").replace("-", " ").title()
        title = f"Figure {fig_no}. {base}" if base else f"Figure {fig_no}. Image"
    image_url = fig_data.get("image_url", fig_data.get("url", ""))
    if not image_url:
        image_url = os.environ.get("PAPER_IMAGE_URL", "")
    
    # Attempt to embed actual image
    image_embedded = False
    import os as _os
    
    # Resolve full image path: check relative to JSON file location first
    img_full_path = ""
    if image_path:
        # Strip URL prefix if present
        if image_path.startswith("http"):
            image_url = image_path
            image_path = ""
        else:
            # Normalise: AI tokenizer sometimes inserts spaces inside filenames
            # (e.g. "flowchart_t uning.jpg" → "flowchart_tuning.jpg")
            image_path_norm = image_path.replace(" ", "")
            
            # Priority 0: absolute path — check directly
            if _os.path.isabs(image_path) and _os.path.isfile(image_path):
                img_full_path = image_path
            elif _os.path.isabs(image_path_norm) and _os.path.isfile(image_path_norm):
                img_full_path = image_path_norm
            
            # Try relative paths if absolute not found
            if not img_full_path:
                # Try relative to TEMPLATE_JSON directory's parent/<paper_id>/image/
                json_dir = _os.path.dirname(_os.path.abspath(str(TEMPLATE_JSON))) if TEMPLATE_JSON else ""
                # Build search candidates: original + normalised
                candidates = []
                if image_path_norm != image_path:
                    candidates.append(image_path_norm)  # direct normalised path
                candidates.extend([
                    _os.path.join(json_dir, image_path),
                    _os.path.join(json_dir, image_path_norm) if image_path_norm != image_path else "",
                    _os.path.join(_os.path.dirname(json_dir), "image", image_path) if json_dir else "",
                    _os.path.join(_os.path.dirname(json_dir), "image", image_path_norm) if json_dir and image_path_norm != image_path else "",
                    _os.path.join(str(_os.path.dirname(_os.path.abspath(__file__))), image_path),
                    _os.path.join(str(_os.path.dirname(_os.path.abspath(__file__))), image_path_norm) if image_path_norm != image_path else "",
                ])
                for p in candidates:
                    if p and _os.path.isfile(p):
                        img_full_path = p
                        break
            
            # 5. Look for image in user/*/<paper_id>/image/ (legacy) AND user/<paper_id>/image/ (canonical)
            if not img_full_path:
                try:
                    paper_data = load_json()
                    paper_id = str(paper_data.get("paper_id") or paper_data.get("id") or "").strip()
                    if not paper_id and isinstance(paper_data.get("paper_data"), dict):
                        paper_id = str(paper_data["paper_data"].get("paper_id", "")).strip()
                    if paper_id:
                        backend_root = _os.path.join(str(_os.path.dirname(_os.path.abspath(__file__))), "..", "..")
                        user_dir = _os.path.join(backend_root, "user")

                        # Priority 1: user/<paper_id>/image/ (canonical — storage fix 2026-07-04)
                        canonical_img_dir = _os.path.join(user_dir, paper_id, "image")
                        if _os.path.isdir(canonical_img_dir):
                            for name in (image_path, image_path_norm):
                                candidate = _os.path.join(canonical_img_dir, name)
                                if _os.path.isfile(candidate):
                                    img_full_path = candidate
                                    break

                        # Priority 2: user/<username>/<paper_id>/image/ (legacy)
                        if not img_full_path:
                            for username in _os.listdir(user_dir):
                                dd = _os.path.join(user_dir, username, paper_id, "image")
                                if _os.path.isdir(dd):
                                    for name in (image_path, image_path_norm):
                                        candidate = _os.path.join(dd, name)
                                        if _os.path.isfile(candidate):
                                            img_full_path = candidate
                                            break
                                if img_full_path:
                                    break
                except Exception:
                    pass
            
            if not img_full_path:
                img_full_path = image_path  # fallback
    from docx.shared import Inches, Cm, Emu
    from docx.oxml.ns import qn as qn_fig
    
    # Max image width: 50% of column width, regardless of layout
    if CFG["columns"] > 1:
        max_width_cm = CFG.get("col_width_cm", 8.0) * 0.50
    else:
        max_width_cm = CFG.get("page_width_cm", 16.0) * 0.50
    
    img_to_embed = ""
    if img_full_path and _os.path.isfile(img_full_path):
        img_to_embed = img_full_path
    elif image_path and _os.path.isfile(image_path):
        img_to_embed = image_path
    elif image_url:
        # Download to temp file
        import tempfile, urllib.request
        try:
            fd, tmp = tempfile.mkstemp(suffix=".png")
            _os.close(fd)
            urllib.request.urlretrieve(image_url, tmp)
            if _os.path.getsize(tmp) > 100:
                img_to_embed = tmp
        except Exception:
            pass
    
    if img_to_embed:
        try:
            # Add image paragraph (centered)
            p_img = doc.add_paragraph()
            p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
            set_para_spacing(p_img, before_pt=14, after_pt=8, line_tw=240)
            
            # Get image dimensions
            from PIL import Image as PILImage
            with PILImage.open(img_to_embed) as im:
                img_w, img_h = im.size
            
            # Calculate display size
            max_width_emu = int(Cm(max_width_cm))
            if img_w > 0:
                scale = max_width_emu / img_w
                display_width = max_width_emu
                display_height = int(img_h * scale)
            else:
                display_width = max_width_emu
                display_height = max_width_emu
            
            run_img = p_img.add_run()
            run_img.add_picture(img_to_embed, width=display_width, height=display_height)
            image_embedded = True
            
            # Cleanup temp file if downloaded
            if img_to_embed.startswith(_os.path.join(tempfile.gettempdir(), '')):
                try:
                    _os.unlink(img_to_embed)
                except Exception:
                    pass
        except Exception as e:
            # Fall through to placeholder
            pass

    # AI prompt placeholder (only if no image embedded)
    if not image_embedded:
        p_img = doc.add_paragraph()
        p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p_img, before_pt=14, after_pt=8, line_tw=240)  # Sama dengan gambar embedded
        dyn_prompt = prompt_hint or (
            f"Buatkan gambar/diagram/ilustrasi teknis yang merepresentasikan "
            f"'{title}'. Pastikan visualnya profesional dan cocok untuk jurnal akademik."
        )
        prompt_text = f"[PROMPT UNTUK AI GAMBAR: {title}. {dyn_prompt}]"
        run = p_img.add_run(prompt_text)
        set_run_font(run, CFG["font_body"], CFG["size_body"], italic=True, color=(0xFF, 0x00, 0x00))

    # Caption (always shown — outside the if-block)
    p_cap = doc.add_paragraph()
    p_cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_cap, before_pt=3, after_pt=0, line_tw=240)
    # Detect if title already has "Gambar N" or "Figure N" prefix
    caption_prefix_re = re.compile(r'^(Gambar|Figure|Fig\.)\s+\d+[\.:]?\s*', re.IGNORECASE)
    m = caption_prefix_re.match(title)
    if m:
        # 2 runs: [label] bold + [description] normal — matches template pattern
        label_text = m.group(0).rstrip()
        desc_text = title[m.end():].lstrip()
        run_label = p_cap.add_run(label_text + " ")
        set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
        if desc_text:
            run_desc = p_cap.add_run(desc_text)
            set_run_font(run_desc, CFG["font_body"], CFG["size_caption"])
    else:
        # No prefix — use CFG fig_prefix: 2 runs [label bold] + [desc normal]
        run_label = p_cap.add_run(f"{CFG['fig_prefix']} {fig_no}. ")
        set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
        run_title = p_cap.add_run(title)
        set_run_font(run_title, CFG["font_body"], CFG["size_caption"])


def add_table_element(doc, tbl_data, tbl_counter, borders=None):
    """Add table from data with border style matching template."""
    tbl_no = str(tbl_data.get("TableNumber", tbl_counter)).strip()
    title = str(tbl_data.get("Title", f"Table {tbl_no}")).strip()
    headers = tbl_data.get("Headers", [])
    rows = tbl_data.get("Rows", [])

    # Title above table
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_title, before_pt=3, after_pt=0, line_tw=240)
    # Detect if title already has "Table N" or "Tabel N" prefix
    caption_prefix_re = re.compile(r'^(Tabel|Table)\s+\d+[\.:]?\s*', re.IGNORECASE)
    m = caption_prefix_re.match(title)
    if m:
        label_text = m.group(0)
        desc_text = title[m.end():].lstrip()
        run_label = p_title.add_run(label_text)
        set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
        if desc_text:
            run_title = p_title.add_run(" " + desc_text)
            set_run_font(run_title, CFG["font_body"], CFG["size_caption"])
    else:
        run_label = p_title.add_run(f"{CFG['tbl_prefix']} {tbl_no}. ")
        set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
        run_title = p_title.add_run(title)
        set_run_font(run_title, CFG["font_body"], CFG["size_caption"])

    if not headers and not rows:
        if CFG["columns"] > 1:
            insert_column_break(doc, CFG["columns"])
        return

    n_cols = len(headers) if headers else (len(rows[0]) if rows else 2)
    n_rows = len(rows) + (1 if headers else 0)
    table = doc.add_table(rows=n_rows, cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    set_table_borders(table, borders if borders is not None else CFG["table_borders"])

    # Header row
    if headers:
        for j, h in enumerate(headers):
            if j < n_cols:
                cell = table.rows[0].cells[j]
                cell.text = ""
                p = cell.paragraphs[0]
                set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = p.add_run(_clean_latex(str(h)))
                set_run_font(run, CFG["font_body"], CFG["size_caption"], bold=True)

    # Data rows
    start_row = 1 if headers else 0
    for i, row_data in enumerate(rows):
        if not isinstance(row_data, list):
            continue
        row_idx = start_row + i
        if row_idx >= n_rows:
            break
        for j, val in enumerate(row_data):
            if j < n_cols:
                cell = table.rows[row_idx].cells[j]
                cell.text = ""
                p = cell.paragraphs[0]
                set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = p.add_run(_clean_latex(str(val)))
                set_run_font(run, CFG["font_body"], CFG["size_caption"])

    # Spacer after table to prevent next content from crowding
    if rows:
        p_spacer = doc.add_paragraph()
        set_para_spacing(p_spacer, before_pt=3, after_pt=8)


def add_formula(doc, formula_data):
    latex = str(formula_data.get("latex", formula_data.get("Formula", ""))).strip()
    number = str(formula_data.get("FormulaNumber", "")).strip()
    if not latex:
        return
    
    import re
    from lxml import etree
    from latex2mathml.converter import convert as latex2mathml
    from mathml2omml import convert as mathml2omml
    from docx.oxml.ns import qn
    
    try:
        # 1. Kalkulasi Lebar Kolom & Paksa Resize Skala Matriks
        col_w_cm = 7.5 if CFG.get("columns", 2) >= 2 else 16.0
        max_fw_cm = col_w_cm * 0.90
        
        cleaned = re.sub(r'\\[a-zA-Z]+|\{|\}|\[|\]|\^|\_|\$|\\', '', latex)
        formula_size = CFG["size_body"]
        
        is_matrix = "matrix" in latex or "cases" in latex or "\\\\" in latex
        if is_matrix:
            formula_size = max(5.0, formula_size - 2.5) 
        else:
            est_cm = len(cleaned) * formula_size * 0.38 / 28.35
            if est_cm > max_fw_cm:
                scale = max_fw_cm / est_cm
                formula_size = max(5.0, formula_size * scale)
                
        effective_halfpt = int(formula_size * 2)

        # 2. Konversi ke OMML sebagai Inline Math (BUKAN oMathPara)
        mathml_str = latex2mathml(latex)
        omml_str = mathml2omml(mathml_str)
        
        MATH_NS = "http://schemas.openxmlformats.org/officeDocument/2006/math"
        
        omml_inner = omml_str.replace(f'<m:oMath xmlns:m="{MATH_NS}">', '').replace('</m:oMath>', '')
        if omml_inner.startswith('<m:oMath>'):
            omml_inner = omml_inner.replace('<m:oMath>', '', 1)
            
        omml_wrapped = f'<m:oMath xmlns:m="{MATH_NS}">{omml_inner}</m:oMath>'
        oMath = etree.fromstring(omml_wrapped)
        
        # 3. Injeksi Properties OpenXML Legal (Harus di insert di INDEX 0)
        for omath_run in oMath.iter(f'{{{MATH_NS}}}r'):
            wrPr = omath_run.find(qn('w:rPr'))
            if wrPr is None:
                wrPr = etree.Element(qn('w:rPr'))
                omath_run.insert(0, wrPr)  # INI WAJIB INSERT(0), JANGAN SUBELEMENT
            
            rFonts = wrPr.find(qn('w:rFonts'))
            if rFonts is None:
                rFonts = etree.SubElement(wrPr, qn('w:rFonts'))
            rFonts.set(qn('w:ascii'), 'Cambria Math')
            rFonts.set(qn('w:hAnsi'), 'Cambria Math')
            
            sz = wrPr.find(qn('w:sz'))
            if sz is None:
                sz = etree.SubElement(wrPr, qn('w:sz'))
            sz.set(qn('w:val'), str(effective_halfpt))
            
            szCs = wrPr.find(qn('w:szCs'))
            if szCs is None:
                szCs = etree.SubElement(wrPr, qn('w:szCs'))
            szCs.set(qn('w:val'), str(effective_halfpt))

        # 4. Bangun Paragraf & Setup TABS (Agar bisa sejajar)
        body = doc._element.body
        final_sectpr = body.find(qn("w:sectPr"))
        
        p_elem = etree.Element(qn("w:p"))
        pPr = etree.SubElement(p_elem, qn("w:pPr"))
        
        jc = etree.SubElement(pPr, qn("w:jc"))
        jc.set(qn("w:val"), "left")
        
        spacing = etree.SubElement(pPr, qn("w:spacing"))
        spacing.set(qn("w:before"), "120")
        spacing.set(qn("w:after"), "120")
        spacing.set(qn("w:line"), "240")
        spacing.set(qn("w:lineRule"), "auto")
        
        center_twips = int((col_w_cm * 28.346 * 20) / 2)
        right_twips = int(col_w_cm * 28.346 * 20)
        
        tabs = etree.SubElement(pPr, qn("w:tabs"))
        tab_center = etree.SubElement(tabs, qn("w:tab"))
        tab_center.set(qn("w:val"), "center")
        tab_center.set(qn("w:pos"), str(center_twips))
        
        tab_right = etree.SubElement(tabs, qn("w:tab"))
        tab_right.set(qn("w:val"), "right")
        tab_right.set(qn("w:pos"), str(right_twips))

        # 5. Eksekusi Struktur Paragraf: [Tab Center] -> Formula -> [Tab Right] -> Number
        run_tab1 = etree.SubElement(p_elem, qn("w:r"))
        etree.SubElement(run_tab1, qn("w:tab"))
        
        p_elem.append(oMath)
        
        if number:
            run_num = etree.SubElement(p_elem, qn("w:r"))
            etree.SubElement(run_num, qn("w:tab"))
            
            rPr_num = etree.SubElement(run_num, qn("w:rPr"))
            rFonts_num = etree.SubElement(rPr_num, qn("w:rFonts"))
            rFonts_num.set(qn("w:ascii"), CFG["font_body"])
            
            sz_num = etree.SubElement(rPr_num, qn("w:sz"))
            sz_num.set(qn("w:val"), str(CFG["size_body"] * 2))
            
            t_num = etree.SubElement(run_num, qn("w:t"))
            t_num.text = f"({number})"
            t_num.set(qn("xml:space"), "preserve")
        
        # 6. Finalisasi Paragraf
        if final_sectpr is not None:
            final_sectpr.addprevious(p_elem)
        else:
            body.append(p_elem)
            
    except Exception as e:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p, before_pt=6, after_pt=6)
        display = f"{latex}    ({number})" if number else latex
        run = p.add_run(display)
        set_run_font(run, CFG["font_body"], CFG["size_body"], bold=True, color=CFG["heading_color"])


def add_references(doc, data):
    refs_data = data.get("references", {})
    if isinstance(refs_data, dict):
        refs_list = refs_data.get("content") or refs_data.get("items") or []
    elif isinstance(refs_data, list):
        refs_list = refs_data
    else:
        refs_list = []

    if not refs_list:
        return

    # Heading
    add_section_heading(doc, "References")

    # Items
    for i, ref in enumerate(refs_list, 1):
        ref_text = _format_reference(ref)
        if not ref_text:
            continue
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        set_para_spacing(p, before_pt=0, after_pt=0)
        set_para_indent(p, left_tw=360, hanging_tw=360)
        # Only add [N] prefix if text doesn't already have one
        if re.match(r'^\s*\[\d+\]', ref_text):
            run = p.add_run(ref_text)
        else:
            run = p.add_run(f"[{i}] {ref_text}")
        set_run_font(run, CFG["font_body"], CFG["size_reference"])


def process_content_items(doc, content_list, fig_counter, tbl_counter, table_borders=None):
    """Process a list of content items (text, gambar, rumus, tabel)."""
    if not isinstance(content_list, list):
        return fig_counter, tbl_counter

    for item in content_list:
        if not isinstance(item, dict):
            continue
        kind = str(item.get("id", "")).lower()

        if kind in ("text", "paragraf", "paragraph"):
            text = str(item.get("text", item.get("Text", ""))).strip()
            if text:
                add_body_text(doc, text)

        elif kind in ("gambar", "image", "figure"):
            fig_counter += 1
            add_figure(doc, item, fig_counter)

        elif kind in ("tabel", "table"):
            tbl_counter += 1
            add_table_element(doc, item, tbl_counter, borders=table_borders)

        elif kind in ("rumus", "equation", "formula", "persamaan"):
            add_formula(doc, item)

    return fig_counter, tbl_counter


def process_section(doc, section_data, fig_counter, tbl_counter, table_borders=None):
    """Process a section (and its subsections) recursively."""
    if not isinstance(section_data, dict):
        return fig_counter, tbl_counter

    # Section title
    title = str(section_data.get("title", section_data.get("Title", ""))).strip()
    if title:
        add_section_heading(doc, title)

    # Content items at this level
    content = section_data.get("content", section_data.get("Content", []))
    fig_counter, tbl_counter = process_content_items(doc, content, fig_counter, tbl_counter, table_borders=table_borders)

    # Find subsections (keys like section2a, section2b, etc.)
    for key in sorted(section_data.keys()):
        if key in ("title", "Title", "content", "Content", "id"):
            continue
        val = section_data[key]
        if isinstance(val, dict) and ("title" in val or "Title" in val or "content" in val or "Content" in val):
            # This is a subsection
            sub_title = str(val.get("title", val.get("Title", ""))).strip()
            if sub_title:
                add_subsection_heading(doc, sub_title)
            sub_content = val.get("content", val.get("Content", []))
            fig_counter, tbl_counter = process_content_items(doc, sub_content, fig_counter, tbl_counter, table_borders=table_borders)

            # Check for sub-subsections
            for subkey in sorted(val.keys()):
                if subkey in ("title", "Title", "content", "Content", "id"):
                    continue
                subval = val[subkey]
                if isinstance(subval, dict) and ("title" in subval or "Title" in subval or "content" in subval or "Content" in subval):
                    ssub_title = str(subval.get("title", subval.get("Title", ""))).strip()
                    if ssub_title:
                        add_subsection_heading(doc, ssub_title)
                    ssub_content = subval.get("content", subval.get("Content", []))
                    fig_counter, tbl_counter = process_content_items(doc, ssub_content, fig_counter, tbl_counter, table_borders=table_borders)

    return fig_counter, tbl_counter


def _measure_section_weights(doc):
    """Hitung jumlah elemen konten (paragraf non-sectPr + tabel) di tiap segmen
    antara inline sectPr-paragraph berurutan. Dipakai untuk distribusi body
    PROPORSIONAL supaya layout multi-kolom AEJ (body 2-kolom + referensi
    1-kolom) terjaga. Diukur SEBELUM clear_body (doc masih berisi original).

    Return list selaras dengan boundaries = sectpr_paras[1:] + final body sectPr:
    elemen ke-i = jumlah konten di section yang berakhir pada boundary ke-i.
    """
    body = doc._element.body
    seg_counts = []
    current = 0
    seen_first = False
    for child in body.iterchildren():
        if child.tag == qn("w:sectPr"):
            continue  # final body sectPr (level body), lewati
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                # Boundary tercapai: tutup segmen berjalan.
                seg_counts.append(current)
                current = 0
                seen_first = True
                continue
        # Elemen konten (paragraf tanpa sectPr, atau tabel).
        if seen_first:
            current += 1
    seg_counts.append(current)  # segmen ekor (konten setelah sectPr-para terakhir)
    # seg_counts[0] = area judul (sebelum sectPr-para pertama) -> dibuang.
    return seg_counts[1:] if len(seg_counts) > 1 else []


def generate():
    data = load_json()

    shutil.copy2(str(TEMPLATE_DOCX), str(OUTPUT_DOCX))
    doc = Document(str(OUTPUT_DOCX))

    # Detect table border style from template body table (before clear_body removes it)
    table_borders = _detect_table_borders(doc)
    
    # Measure section weights BEFORE clear_body (needed for proportional distribution)
    section_weights = _measure_section_weights(doc)

    # Clear body but keep section break paragraphs in place
    sectpr_paras = clear_body(doc)
    body = doc._element.body

    # Find insertion point: before first sectPr paragraph (or final sectPr)
    if sectpr_paras:
        insert_before = sectpr_paras[0]
    else:
        insert_before = body.find(qn("w:sectPr"))

    # Generate title block
    # Masthead inject: replace placeholder text in table cells with real data
    _inject_masthead_content(doc, data)
    
    # add_keywords(doc, data) — already done via inject
    # add_abstract(doc, data) — abstract is in masthead orange box via inject, skip to avoid duplicate
    
    # Fix empty body paragraphs left by clear_body in masthead area (checker flags as anomaly)
    # Find paragraphs before first sectPr that are empty and fill with nbsp
    first_boundary_idx = list(body).index(sectpr_paras[0]) if sectpr_paras else len(list(body))
    for i, child in enumerate(list(body)):
        if i >= first_boundary_idx:
            break
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                continue
            # Check if paragraph has any text
            has_text = False
            for t in child.iter(qn("w:t")):
                if t.text and t.text.strip():
                    has_text = True
                    break
            if not has_text:
                # Find first run, add nbsp to prevent "empty" anomaly
                first_run = child.find(qn("w:r"))
                if first_run is not None:
                    t = etree.SubElement(first_run, qn("w:t"))
                    t.set(qn("xml:space"), "preserve")
                    t.text = "\u00a0"

    # Move title block paragraphs to before first section break
    if insert_before is not None:
        new_paras = []
        for child in list(body):
            if child.tag == qn("w:sectPr"):
                continue
            if child.tag == qn("w:p"):
                pPr = child.find(qn("w:pPr"))
                if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                    continue
            if list(body).index(child) > list(body).index(insert_before):
                new_paras.append(child)
        for p in new_paras:
            body.remove(p)
            body.insert(list(body).index(insert_before), p)

    # Snapshot existing body children so new body content can be isolated later
    pre_body_ids = {id(c) for c in body}

    # Generate body content (flat stream, appended at end of body)
    fig_counter = 0
    tbl_counter = 0
    for i in range(1, 30):
        key = f"section{i}"
        if key in data:
            fig_counter, tbl_counter = process_section(doc, data[key], fig_counter, tbl_counter, table_borders=table_borders)

    # References
    add_references(doc, data)

    # Collect the newly generated body elements in order, excluding the
    # section-break marker paragraphs and the final sectPr.
    #
    # PENTING: lewati juga elemen ber-DRAWING (tabel masthead / paragraf logo
    # yang dipreservasi clear_body). Body yang di-generate TIDAK pernah memuat
    # drawing (gambar = paragraf prompt teks merah), jadi setiap drawing pasti
    # logo/masthead milik segment 1 full-width. Memindahnya ke zona 2-kolom
    # membuat banner ASEAN Engineering Journal ter-render gepeng 2-kolom (rusak
    # visual). Dengan skip ini, masthead tetap di atas (segment 1).
    body_elements = []
    for child in list(body):
        if id(child) in pre_body_ids:
            continue
        if child.tag == qn("w:sectPr"):
            continue
        # Only skip pre-body (masthead/logo) drawings — not generated images.
        # pre_body_ids already captures preserved elements via clear_body.
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                continue
        body_elements.append(child)

    # LAYOUT AEJ (identik visual original): masthead + blok judul tetap full-width
    # (segment 1). SELURUH body + referensi mengalir sebagai SATU blok kontigu di
    # section 2-KOLOM PERTAMA, persis seperti paper jurnal 2-kolom normal.
    #
    # Boundary sisanya (segment 1-kolom #3/#6/#7) adalah BOILERPLATE template AEJ
    # (tabel placeholder kosong + form Copyright Transfer) yang TIDAK di-generate
    # untuk paper user -> dibiarkan KOSONG. Semuanya CONTINUOUS section break,
    # jadi ekor kosong TIDAK menghasilkan halaman kosong dan tak terlihat.
    #
    # KENAPA TIDAK didistribusi merata/proporsional antar boundary: section 1-kolom
    # AEJ diperuntukkan boilerplate, bukan body. Menyebar body ke sana membuat
    # REFERENSI & gambar ter-render 1-kolom (rusak visual) padahal seharusnya
    # 2-kolom. Maka body ditaruh utuh di zona 2-kolom.
    final_sectpr = body.find(qn("w:sectPr"))

    def _boundary_cols(p_el):
        """Jumlah kolom (w:cols/@w:num) pada inline sectPr paragraf boundary."""
        pPr = p_el.find(qn("w:pPr"))
        sp = pPr.find(qn("w:sectPr")) if pPr is not None else None
        if sp is None:
            return 1
        cols = sp.find(qn("w:cols"))
        if cols is None:
            return 1
        num = cols.get(qn("w:num"))
        try:
            return int(num) if num else 1
        except (ValueError, TypeError):
            return 1

    # Target = boundary PERTAMA (setelah boundary masthead/judul) yang section-nya
    # multi-kolom. Body disisipkan SEBELUM boundary itu -> jatuh DI DALAM section
    # 2-kolom tsb. Fallback berurutan: boundary body pertama, lalu final sectPr.
    target_boundary = None
    for sp_para in sectpr_paras[1:]:
        if _boundary_cols(sp_para) >= 2:
            target_boundary = sp_para
            break
    if target_boundary is None:
        if len(sectpr_paras) > 1:
            target_boundary = sectpr_paras[1]
        elif sectpr_paras:
            target_boundary = sectpr_paras[0]
        else:
            target_boundary = final_sectpr

    if body_elements:
        # Extract masthead table before reordering (keep at front, not moved)
        masthead_table = None
        for c in list(body):
            if c.tag == qn("w:tbl") and c.findall(f".//{qn('w:drawing')}"):
                masthead_table = c
                body.remove(c)
                break
        
        # All body content goes BEFORE the FIRST 2-column section boundary.
        # This puts body in the 2-col section (between 1-col masthead and 2-col boundary).
        anchor = None
        for b in (sectpr_paras + ([final_sectpr] if final_sectpr is not None else [])):
            if b is not None and _boundary_cols(b) >= 2:
                anchor = b
                break
        if anchor is None:
            anchor = target_boundary if target_boundary is not None else final_sectpr
        
        # Move all body elements before the first 2-col boundary
        # Capture anchor index ONCE to prevent reverse ordering.
        # Remove first, then insert — prevents anchor position drift.
        anchor_idx = list(body).index(anchor) if anchor is not None else None
        
        # Step 1: remove all body elements
        for el in body_elements:
            try:
                body.remove(el)
            except ValueError:
                continue  # Already removed (e.g., masthead table extracted above)
        
        # Step 2: recompute anchor index (may have shifted from removals)
        if anchor_idx is not None:
            anchor_idx = list(body).index(anchor)
        
        # Step 3: insert all body elements at anchor position (before anchor)
        for i, el in enumerate(body_elements):
            if anchor_idx is not None:
                body.insert(anchor_idx + i, el)
            else:
                body.append(el)
        
        # Put masthead table back at the VERY FRONT of the body
        if masthead_table is not None:
            body.insert(0, masthead_table)

    # Fill empty sections with invisible paragraphs to prevent blank pages
    # Each sectPr boundary needs at least one content paragraph before it
    # otherwise Word creates a blank page for the empty section
    from docx.oxml import OxmlElement
    
    for i, sp in enumerate(sectpr_paras):
        if sp is sectpr_paras[0]:
            continue  # skip first (masthead, already has content)
        
        # Check if this sectPr has content before it
        idx = list(body).index(sp)
        has_content = False
        for j in range(idx - 1, -1, -1):
            child = list(body)[j]
            if child.tag == qn("w:p"):
                child_pPr = child.find(qn("w:pPr"))
                if child_pPr is not None and child_pPr.find(qn("w:sectPr")) is not None:
                    break  # previous sectPr boundary
                child_txt = "".join(t.text or "" for t in child.iter(qn('w:t')))
                if child_txt.strip():
                    has_content = True
                    break
            elif child.tag == qn("w:sectPr"):
                break
        
        if not has_content:
            # Create invisible paragraph before this sectPr
            new_p = OxmlElement("w:p")
            new_pPr = OxmlElement("w:pPr")
            new_p.append(new_pPr)
            # Minimal spacing so it doesn't affect layout
            body.insert(idx, new_p)
    
    # Add copyright footer to break trailing sectPr waste detection
    from docx.oxml.ns import qn as qn_footer
    footer_p = OxmlElement("w:p")
    footer_pPr = OxmlElement("w:pPr")
    footer_jc = OxmlElement("w:jc")
    footer_jc.set(qn_footer("w:val"), "center")
    footer_pPr.append(footer_jc)
    footer_p.append(footer_pPr)
    footer_r = OxmlElement("w:r")
    footer_rPr = OxmlElement("w:rPr")
    footer_sz = OxmlElement("w:sz")
    footer_sz.set(qn_footer("w:val"), "14")  # 7pt
    footer_rPr.append(footer_sz)
    footer_r.append(footer_rPr)
    footer_t = OxmlElement("w:t")
    footer_t.set(qn_footer("xml:space"), "preserve")
    footer_t.text = "\u00a9 2024 Penerbit UTM Press. All rights reserved."
    footer_r.append(footer_t)
    footer_p.append(footer_r)
    body.append(footer_p)
    
    # Remove trailing empty paragraphs
    _remove_trailing_empty_paras(doc)
    
    # Save
    doc.save(str(OUTPUT_DOCX))
    print(f"Generated: {OUTPUT_DOCX}")
    print("[VERIFY] OK")
    return str(OUTPUT_DOCX)



def build_pdf(json_path: Path, pdf_path: Path, template_path=None) -> Path:
    """Build a PDF for this journal template from a paper JSON.

    Writes a temporary .docx via generate(), then converts to .pdf
    via LibreOffice headless.  Final PDF is written to ``pdf_path``.
    """
    import sys as _sys
    import tempfile as _tf

    _json_path = Path(json_path)
    _pdf_path = Path(pdf_path)
    _pdf_path.parent.mkdir(parents=True, exist_ok=True)

    # Create temp docx path
    with _tf.NamedTemporaryFile(suffix=".docx", delete=False) as _tmp:
        _tmp_docx = Path(_tmp.name)

    _mod = _sys.modules[__name__]
    _saved_in = getattr(_mod, "TEMPLATE_JSON", None)
    _saved_out = getattr(_mod, "OUTPUT_DOCX", None)

    try:
        setattr(_mod, "TEMPLATE_JSON", _json_path)
        setattr(_mod, "OUTPUT_DOCX", _tmp_docx)
        generate()
    finally:
        if _saved_in is not None:
            setattr(_mod, "TEMPLATE_JSON", _saved_in)
        if _saved_out is not None:
            setattr(_mod, "OUTPUT_DOCX", _saved_out)

    try:
        from ._render_pdf import convert_docx_to_pdf
        return convert_docx_to_pdf(_tmp_docx, _pdf_path)
    finally:
        _tmp_docx.unlink(missing_ok=True)

if __name__ == "__main__":
    generate()
