"""
ICOSEGgen.py - Generator DOCX untuk jurnal ICOSEG.
Menggunakan dokumen asli ICOSEG.docx sebagai base template.
Data diambil dari _template.json.
Auto-generated by gen_factory.py.
"""
import json
import copy
import shutil
import re
import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, Cm, Inches, Twips, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml, OxmlElement
from lxml import etree

BASE = Path(__file__).resolve().parent
TEMPLATE_DOCX = BASE / "ICOSEG.docx"
TEMPLATE_JSON = BASE / "_template.json"
OUTPUT_DOCX = BASE / "ICOSEG_output.docx"

CFG = {
    "font_body": "Times New Roman",
    "font_title": "Times New Roman",
    "font_heading": "Times New Roman",
    "size_body": 10,
    "size_title": 14,
    "size_heading1": 10,
    "size_heading2": 10,
    "size_caption": 8,
    "size_reference": 8,
    "columns": 1,
    "first_line_indent_tw": 0,
    "table_borders": "full",
    "fig_prefix": "Fig.",
    "tbl_prefix": "Table",
    "section_heading_upper": True,
}

def _format_reference(item) -> str:
    """Format a reference dict into a citation string."""
    if isinstance(item, str):
        return item.strip()
    if not isinstance(item, dict):
        return str(item).strip()
    text = item.get("text") or item.get("Text") or item.get("value")
    if text:
        return str(text).strip()
    parts = []
    authors = item.get("authors", [])
    if authors:
        parts.append(", ".join(str(a) for a in authors) if isinstance(authors, list) else str(authors))
    year = item.get("year")
    if year:
        parts.append(f"({year})")
    title = item.get("title", "")
    if title:
        parts.append(f'"{title},"')
    jname = item.get("journal") or item.get("conference") or ""
    if jname:
        parts.append(str(jname) + ",")
    vol = item.get("volume", "")
    if vol:
        parts.append(f"vol. {vol},")
    issue = item.get("issue", "")
    if issue:
        parts.append(f"no. {issue},")
    pages = item.get("pages", "")
    if pages:
        parts.append(f"pp. {pages},")
    doi = item.get("doi", "")
    if doi:
        parts.append(f"doi: {doi}.")
    url = item.get("url", "")
    if url:
        accessed = item.get("accessed", "")
        parts.append(f"[Online]. Available: {url}" + (f" [Accessed: {accessed}]." if accessed else "."))
    publisher = item.get("publisher", "")
    if publisher and not jname:
        location = item.get("location", "")
        parts.append(f"{location}: {publisher}." if location else f"{publisher}.")
    result = " ".join(str(p) for p in parts if p).strip()
    result = result.replace(" , ", ", ").replace(" .", ".")
    if result.endswith(","):
        result = result[:-1] + "."
    if not result.endswith("."):
        result = result + "."
    return result

def load_json():
    with open(TEMPLATE_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def set_run_font(run, font_name=None, size_pt=None, bold=None, italic=None, color=None):
    if font_name:
        run.font.name = font_name
        rPr = run._element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = OxmlElement("w:rFonts")
            rPr.insert(0, rFonts)
        rFonts.set(qn("w:ascii"), font_name)
        rFonts.set(qn("w:hAnsi"), font_name)
        rFonts.set(qn("w:cs"), font_name)
    if size_pt:
        run.font.size = Pt(size_pt)
    if bold is not None:
        run.bold = bold
    if italic is not None:
        run.italic = italic
    if color:
        run.font.color.rgb = RGBColor(*color)


def set_para_spacing(para, before_pt=None, after_pt=None, line_tw=276):
    pf = para.paragraph_format
    if before_pt is not None:
        pf.space_before = Pt(before_pt)
    if after_pt is not None:
        pf.space_after = Pt(after_pt)
    if line_tw is not None:
        pPr = para._element.get_or_add_pPr()
        spacing = pPr.find(qn("w:spacing"))
        if spacing is None:
            spacing = OxmlElement("w:spacing")
            pPr.append(spacing)
        spacing.set(qn("w:line"), str(line_tw))
        spacing.set(qn("w:lineRule"), "auto")


def set_para_indent(para, first_line_tw=None, left_tw=None, hanging_tw=None):
    pPr = para._element.get_or_add_pPr()
    ind = pPr.find(qn("w:ind"))
    if ind is None:
        ind = OxmlElement("w:ind")
        pPr.append(ind)
    if first_line_tw is not None:
        ind.set(qn("w:firstLine"), str(first_line_tw))
    if left_tw is not None:
        ind.set(qn("w:left"), str(left_tw))
    if hanging_tw is not None:
        ind.set(qn("w:hanging"), str(hanging_tw))
        if ind.get(qn("w:firstLine")):
            del ind.attrib[qn("w:firstLine")]


def set_table_borders(table, style="three_line"):
    tblPr = table._element.find(qn("w:tblPr"))
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        table._element.insert(0, tblPr)
    borders = tblPr.find(qn("w:tblBorders"))
    if borders is not None:
        tblPr.remove(borders)
    borders = OxmlElement("w:tblBorders")

    if style == "three_line":
        for side in ("top", "bottom", "insideH"):
            el = OxmlElement(f"w:{side}")
            el.set(qn("w:val"), "single")
            el.set(qn("w:sz"), "4")
            el.set(qn("w:space"), "0")
            el.set(qn("w:color"), "000000")
            borders.append(el)
        for side in ("left", "right", "insideV"):
            el = OxmlElement(f"w:{side}")
            el.set(qn("w:val"), "none")
            el.set(qn("w:sz"), "0")
            el.set(qn("w:space"), "0")
            el.set(qn("w:color"), "auto")
            borders.append(el)
    elif style == "full":
        for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
            el = OxmlElement(f"w:{side}")
            el.set(qn("w:val"), "single")
            el.set(qn("w:sz"), "4")
            el.set(qn("w:space"), "0")
            el.set(qn("w:color"), "000000")
            borders.append(el)
    elif style == "partial":
        for side in ("top", "bottom", "insideH", "insideV"):
            el = OxmlElement(f"w:{side}")
            el.set(qn("w:val"), "single")
            el.set(qn("w:sz"), "4")
            el.set(qn("w:space"), "0")
            el.set(qn("w:color"), "auto")
            borders.append(el)
    elif style == "none":
        for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
            el = OxmlElement(f"w:{side}")
            el.set(qn("w:val"), "none")
            el.set(qn("w:sz"), "0")
            el.set(qn("w:space"), "0")
            el.set(qn("w:color"), "auto")
            borders.append(el)

    tblPr.append(borders)


def clear_body(doc):
    """Clear body text/tables but keep section break paragraphs and top image paragraphs/tables (logos)."""
    body = doc._element.body
    sectpr_paras = []
    logo_paras = []
    logo_tables = []

    # First pass: identify logo paragraphs (images in first 3 paragraphs)
    para_count = 0
    for child in body:
        if child.tag == qn("w:p"):
            para_count += 1
            if para_count <= 3:
                # Check if paragraph has image/drawing
                has_image = False
                for run in child.findall(qn("w:r")):
                    if run.findall(qn("w:drawing")):
                        has_image = True
                        break
                if has_image:
                    logo_paras.append(child)

    # Identify logo tables (tables with drawings in first 3 tables)
    table_count = 0
    for child in body:
        if child.tag == qn("w:tbl"):
            table_count += 1
            if table_count <= 3:
                # Check if table has drawing
                has_drawing = len(child.findall(f".//{qn('w:drawing')}")) > 0
                if has_drawing:
                    logo_tables.append(child)

    # Second pass: clear body but preserve logos and section breaks
    for child in list(body):
        if child.tag == qn("w:sectPr"):
            continue
        if child in logo_paras:
            continue  # Preserve logo paragraphs
        if child in logo_tables:
            continue  # Preserve logo tables
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                # Keep this paragraph (it has section break)
                # But clear its text content
                for run in child.findall(qn("w:r")):
                    child.remove(run)
                sectpr_paras.append(child)
                continue
        body.remove(child)
    return sectpr_paras


def distribute_section_breaks(doc, n_breaks):
    """Insert n_breaks section breaks evenly distributed among body paragraphs."""
    if n_breaks <= 0:
        return
    body = doc._element.body
    # Count content paragraphs (exclude final sectPr)
    content_elements = [c for c in body if c.tag != qn("w:sectPr")]
    total = len(content_elements)
    if total == 0:
        return
    # Calculate interval
    interval = max(1, total // (n_breaks + 1))
    # Insert section breaks at intervals (from end to start to preserve indices)
    insert_positions = []
    for i in range(1, n_breaks + 1):
        pos = min(i * interval, total - 1)
        if pos not in insert_positions:
            insert_positions.append(pos)
    # Get final sectPr to copy its properties
    final_sectpr = body.find(qn("w:sectPr"))
    for pos in reversed(insert_positions):
        target = content_elements[pos] if pos < len(content_elements) else content_elements[-1]
        # Add sectPr to this paragraph's pPr (inline section break)
        if target.tag == qn("w:p"):
            pPr = target.find(qn("w:pPr"))
            if pPr is None:
                pPr = OxmlElement("w:pPr")
                target.insert(0, pPr)
            sp = OxmlElement("w:sectPr")
            # Copy page size and margins from final sectPr
            if final_sectpr is not None:
                for prop_tag in ("w:pgSz", "w:pgMar", "w:cols"):
                    orig = final_sectpr.find(qn(prop_tag))
                    if orig is not None:
                        import copy
                        sp.append(copy.deepcopy(orig))
            pPr.append(sp)


def insert_column_break(doc, num_cols):
    """Insert continuous section break to switch column count."""
    if CFG["columns"] <= 1:
        return
    body = doc._element.body
    final_sectpr = body.find(qn("w:sectPr"))
    # Create empty paragraph with sectPr (continuous type)
    p_el = OxmlElement("w:p")
    pPr_el = OxmlElement("w:pPr")
    sp = OxmlElement("w:sectPr")
    # Set type=continuous
    sec_type = OxmlElement("w:type")
    sec_type.set(qn("w:val"), "continuous")
    sp.append(sec_type)
    # Copy page size and margins from final sectPr
    if final_sectpr is not None:
        for prop_tag in ("w:pgSz", "w:pgMar"):
            orig = final_sectpr.find(qn(prop_tag))
            if orig is not None:
                import copy
                sp.append(copy.deepcopy(orig))
    # Set columns
    cols_el = OxmlElement("w:cols")
    cols_el.set(qn("w:num"), str(num_cols))
    sp.append(cols_el)
    pPr_el.append(sp)
    p_el.append(pPr_el)
    # Insert before final sectPr
    if final_sectpr is not None:
        body.insert(list(body).index(final_sectpr), p_el)
    else:
        body.append(p_el)


def remove_trailing_empty_sectpr_paras(doc):
    """Remove empty paragraphs with sectPr at the end of body (fixes blank pages)."""
    body = doc._element.body
    to_remove = []

    # Scan backwards from end
    for child in reversed(list(body)):
        if child.tag == qn("w:sectPr"):
            # Stop at final sectPr
            break
        if child.tag == qn("w:p"):
            pPr = child.find(qn("w:pPr"))
            if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                # This paragraph has a section break
                # Check if it's empty (no runs with text)
                has_content = False
                for run in child.findall(qn("w:r")):
                    t_elem = run.find(qn("w:t"))
                    if t_elem is not None and t_elem.text and t_elem.text.strip():
                        has_content = True
                        break

                if not has_content:
                    # Empty paragraph with sectPr - mark for removal
                    to_remove.append(child)
                else:
                    # Non-empty paragraph - stop scanning
                    break
            else:
                # Paragraph without sectPr - stop scanning
                break
        elif child.tag == qn("w:tbl"):
            # Table - stop scanning (content found)
            break

    # Remove marked paragraphs
    for child in to_remove:
        body.remove(child)

    return len(to_remove)


def add_title(doc, data):
    title = str(data.get("title", "Paper Title")).strip()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p, before_pt=0, after_pt=6)
    run = p.add_run(title)
    set_run_font(run, CFG["font_title"], CFG["size_title"], bold=True)


def add_authors(doc, data):
    authors = data.get("authors", [])
    if not authors:
        return
    # Author names
    names = [a["name"] if isinstance(a, dict) else str(a) for a in authors]
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p, before_pt=6, after_pt=3)
    run = p.add_run(", ".join(names))
    set_run_font(run, CFG["font_title"], CFG["size_body"])

    # Affiliations
    affiliations = set()
    for a in authors:
        if isinstance(a, dict) and a.get("affiliation"):
            affiliations.add(a["affiliation"])
    if affiliations:
        p2 = doc.add_paragraph()
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p2, before_pt=0, after_pt=3)
        run2 = p2.add_run("; ".join(affiliations))
        set_run_font(run2, CFG["font_title"], CFG["size_body"] - 1, italic=True)

    # Emails
    emails = [a.get("email", "") for a in authors if isinstance(a, dict) and a.get("email")]
    if emails:
        p3 = doc.add_paragraph()
        p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p3, before_pt=0, after_pt=6)
        run3 = p3.add_run(", ".join(emails))
        set_run_font(run3, CFG["font_title"], CFG["size_body"] - 1, italic=True)


def add_abstract(doc, data):
    abstract = str(data.get("abstract", "")).strip()
    if not abstract:
        return
    # Label
    p_label = doc.add_paragraph()
    p_label.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_label, before_pt=6, after_pt=3)
    run_label = p_label.add_run("Abstract")
    set_run_font(run_label, CFG["font_body"], CFG["size_body"], bold=True)
    # Content
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=6)
    run = p.add_run(abstract)
    set_run_font(run, CFG["font_body"], CFG["size_body"])


def add_keywords(doc, data):
    keywords = data.get("keywords", [])
    if not keywords:
        return
    if isinstance(keywords, list):
        kw_text = ", ".join(str(k) for k in keywords)
    else:
        kw_text = str(keywords)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=6)
    run_label = p.add_run("Keywords: ")
    set_run_font(run_label, CFG["font_body"], CFG["size_body"], bold=True)
    run_kw = p.add_run(kw_text)
    set_run_font(run_kw, CFG["font_body"], CFG["size_body"], italic=True)


def add_section_heading(doc, title):
    """Add section heading - NO manual numbering (let Word handle it)."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_spacing(p, before_pt=6, after_pt=3)
    display = title.upper() if CFG["section_heading_upper"] else title
    run = p.add_run(display)
    set_run_font(run, CFG["font_heading"], CFG["size_heading1"], bold=True)


def add_subsection_heading(doc, title):
    """Add subsection heading - NO manual numbering."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_para_spacing(p, before_pt=3, after_pt=3)
    run = p.add_run(title)
    set_run_font(run, CFG["font_heading"], CFG["size_heading2"], bold=True)


def _clean_latex(text):
    """Strip inline LaTeX markers dari body text supaya tidak bocor ke output."""
    text = re.sub(r'\$([^$]+)\$', r'\1', text)
    text = re.sub(r'\\mathrm\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\mathbf\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\text\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\hat\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\vec\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\overline\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\sqrt\{([^}]*)\}', r'sqrt(\1)', text)
    text = re.sub(r'\\frac\{([^}]*)\}\{([^}]*)\}', r'(\1/\2)', text)
    text = re.sub(r'\\left[(\[{]', '(', text)
    text = re.sub(r'\\right[)\]}]', ')', text)
    text = re.sub(r'\\begin\{cases\}', '', text)
    text = re.sub(r'\\end\{cases\}', '', text)
    text = re.sub(r'\\approx', chr(8776), text)
    text = re.sub(r'\\times', chr(215), text)
    text = re.sub(r'\\cdot', chr(183), text)
    text = re.sub(r'\\quad', ' ', text)
    text = re.sub(r'\\qquad', '  ', text)
    text = re.sub(r'\\infty', chr(8734), text)
    text = re.sub(r'\\circ', chr(176), text)
    text = re.sub(r'\\alpha', chr(945), text)
    text = re.sub(r'\\beta', chr(946), text)
    text = re.sub(r'\\gamma', chr(947), text)
    text = re.sub(r'\\theta', chr(952), text)
    text = re.sub(r'\\lambda', chr(955), text)
    text = re.sub(r'\\sigma', chr(963), text)
    text = re.sub(r'\\omega', chr(969), text)
    text = re.sub(r'\\pi', chr(960), text)
    text = re.sub(r'\\mu', chr(956), text)
    text = re.sub(r'\\Delta', chr(916), text)
    text = re.sub(r'\\partial', chr(8706), text)
    # Convert subscripts to Unicode subscript characters
    _sub_map = {
        '0': '₀', '1': '₁', '2': '₂', '3': '₃', '4': '₄',
        '5': '₅', '6': '₆', '7': '₇', '8': '₈', '9': '₉',
        'i': 'ᵢ', 'j': 'ⱼ', 'k': 'ₖ', 'l': 'ₗ', 'm': 'ₘ',
        'n': 'ₙ', 'o': 'ₒ', 'p': 'ₚ', 'r': 'ᵣ', 's': 'ₛ',
        't': 'ₜ', 'x': 'ₓ', 'y': 'ᵧ', 'z': 'z',
        'a': 'ₐ', 'e': 'ₑ', 'h': 'ₕ',
    }
    _sup_map = {
        '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴',
        '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹',
        'n': 'ⁿ', 'x': 'ˣ', 'y': 'ʸ',
    }

    def _sub_single(m):
        c = m.group(1)
        return _sub_map.get(c) or c

    def _sup_single(m):
        c = m.group(1)
        return _sup_map.get(c) or c

    def _sub_braced(m):
        s = m.group(1)
        return ''.join(_sub_map.get(c) or c for c in s)

    def _sup_braced(m):
        s = m.group(1)
        return ''.join(_sup_map.get(c) or c for c in s)

    # Braced sub/superscript: _{abc} → ₐᵦc
    text = re.sub(r'_\{([^}]+)\}', _sub_braced, text)
    text = re.sub(r'\^\{([^}]+)\}', _sup_braced, text)
    # Single-char sub/superscript: _i → ᵢ, ^2 → ²
    text = re.sub(r'_([a-zA-Z0-9])', _sub_single, text)
    text = re.sub(r'\^([a-zA-Z0-9])', _sup_single, text)
    text = re.sub(r'\\[a-zA-Z]+', '', text)
    text = re.sub(r'[{}]', '', text)
    # Strip stray single-char artifacts at edges (LLM data noise)
    # Pattern: paired b/i at both edges (LaTeX \b or \i artifact)
    if text.startswith('b') and text.endswith(' b'):
        text = text[1:].rstrip()
        text = text[:-1].rstrip()
    elif text.startswith('i ') and text.endswith(' i'):
        text = text[2:]
        text = text[:-1].rstrip()
    # Math content: strip stray i/b at edges
    _math_chars = set('ᵢⱼₖₗₘₙₒₚᵣₛₜₓᵧ₀₁₂₃₄₅₆₇₈₉ₐₑₕⁿˣʸ⁰¹²³⁴⁵⁶⁷⁸⁹θαπσβγδελμωφψρτηζξχν')
    if any(c in _math_chars for c in text):
        text = re.sub(r'^[ib](?=[A-Z(θαπσβγδελμω])', '', text)
        text = re.sub(r'^[ib]\s+(?=[θαπσβγδελμω])', '', text)
        text = re.sub(r'(?<=\))[ib]$', '', text)
    return text.strip()


def add_body_text(doc, text):
    cleaned = _clean_latex(text)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    set_para_spacing(p, before_pt=0, after_pt=0)
    if CFG["first_line_indent_tw"] > 0:
        set_para_indent(p, first_line_tw=CFG["first_line_indent_tw"])
    run = p.add_run(cleaned)
    set_run_font(run, CFG["font_body"], CFG["size_body"])


def add_figure(doc, fig_data, fig_counter):
    fig_no = str(fig_data.get("ImageNumber", fig_counter)).strip()
    title = _clean_latex(str(fig_data.get("Title", f"Figure {fig_no}")).strip())
    prompt_hint = _clean_latex(str(fig_data.get("Prompt", "")).strip())

    image_path_str = str(fig_data.get("Path", "")).strip()
    # Normalise: AI tokenizer sometimes inserts spaces inside filenames
    image_path_norm = image_path_str.replace(" ", "") if " " in image_path_str else image_path_str
    image_url = str(fig_data.get("url", "")).strip()
    has_image = fig_data.get("hasImage", False)

    # ── Resolve actual image file ────────────────────────────────────────
    actual_image = None
    if image_path_str or image_url:
        candidates = []

        # 1) Absolute path (original + space-normalised)
        if image_path_str and os.path.isabs(image_path_str):
            candidates.append(Path(image_path_str))
            if image_path_norm != image_path_str:
                candidates.append(Path(image_path_norm))

        # 2) Relative to TEMPLATE_JSON's image/ sibling folder
        try:
            json_dir = Path(str(TEMPLATE_JSON)).parent
            paper_dir = json_dir.parent
            image_dir = paper_dir / "image"
            if image_dir.is_dir() and image_path_str:
                candidates.append(image_dir / image_path_str)
                if image_path_norm != image_path_str:
                    candidates.append(image_dir / image_path_norm)
                stem = os.path.splitext(image_path_str)[0]
                if stem:
                    for ext in ('.jpg', '.jpeg', '.png', '.gif', '.webp'):
                        candidates.append(image_dir / f"{stem}{ext}")
        except Exception:
            pass

        # 3) Scan user/*/<paper_id>/image/ (web export: TEMPLATE_JSON is /tmp/)
        try:
            data = load_json()
            _pid = str(data.get("paper_id") or data.get("id") or "").strip()
            if not _pid and isinstance(data.get("paper_data"), dict):
                _pid = str(data["paper_data"].get("paper_id", "")).strip()
            if _pid:
                _udir = Path(__file__).resolve().parent.parent.parent / "user"
                if _udir.is_dir():
                    for _uname in _udir.iterdir():
                        _idir = _uname / _pid / "image"
                        if _idir.is_dir():
                            for _n in (image_path_str, image_path_norm):
                                candidates.append(_idir / _n)
                            break
        except Exception:
            pass

        # 4) Direct path from fig_data
        if image_path_str:
            candidates.append(Path(image_path_str))

        for cand in candidates:
            if cand.exists() and cand.is_file():
                actual_image = cand
                break

    # ── Embed gambar atau fallback prompt ────────────────────────────────
    p_img = doc.add_paragraph()
    p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_img, before_pt=3, after_pt=3)

    if actual_image:
        try:
            run_img = p_img.add_run()
            run_img.add_picture(str(actual_image), width=Inches(5.5))
        except Exception:
            actual_image = None

    if not actual_image:
        # AI prompt fallback (red italic)
        dyn_prompt = prompt_hint or (
            f"Buatkan gambar/diagram/ilustrasi teknis yang merepresentasikan "
            f"'{title}'. Pastikan visualnya profesional dan cocok untuk jurnal akademik."
        )
        prompt_text = f"[PROMPT UNTUK AI GAMBAR: {title}. {dyn_prompt}]"
        run = p_img.add_run(prompt_text)
        set_run_font(run, CFG["font_body"], CFG["size_body"], italic=True, color=(0xFF, 0x00, 0x00))

    # Caption
    p_cap = doc.add_paragraph()
    p_cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_cap, before_pt=3, after_pt=6)
    run_label = p_cap.add_run(f"{CFG['fig_prefix']} {fig_no}. ")
    set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
    run_title = p_cap.add_run(title)
    set_run_font(run_title, CFG["font_body"], CFG["size_caption"])


def add_table_element(doc, tbl_data, tbl_counter):
    tbl_no = str(tbl_data.get("TableNumber", tbl_counter)).strip()
    title = _clean_latex(str(tbl_data.get("Title", f"Table {tbl_no}")).strip())
    headers = tbl_data.get("Headers", [])
    rows = tbl_data.get("Rows", [])

    # Title above table
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_para_spacing(p_title, before_pt=6, after_pt=3)
    run_label = p_title.add_run(f"{CFG['tbl_prefix']} {tbl_no}. ")
    set_run_font(run_label, CFG["font_body"], CFG["size_caption"], bold=True)
    run_title = p_title.add_run(title)
    set_run_font(run_title, CFG["font_body"], CFG["size_caption"])

    if not headers and not rows:
        if CFG["columns"] > 1:
            insert_column_break(doc, CFG["columns"])
        return

    n_cols = len(headers) if headers else (len(rows[0]) if rows else 2)
    n_rows = len(rows) + (1 if headers else 0)
    table = doc.add_table(rows=n_rows, cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    set_table_borders(table, CFG["table_borders"])

    # Header row
    if headers:
        for j, h in enumerate(headers):
            if j < n_cols:
                cell = table.rows[0].cells[j]
                cell.text = ""
                p = cell.paragraphs[0]
                set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = p.add_run(_clean_latex(str(h)))
                set_run_font(run, CFG["font_body"], CFG["size_caption"], bold=True)

    # Data rows
    start_row = 1 if headers else 0
    for i, row_data in enumerate(rows):
        if not isinstance(row_data, list):
            continue
        row_idx = start_row + i
        if row_idx >= n_rows:
            break
        for j, val in enumerate(row_data):
            if j < n_cols:
                cell = table.rows[row_idx].cells[j]
                cell.text = ""
                p = cell.paragraphs[0]
                set_para_spacing(p, before_pt=0, after_pt=0, line_tw=240)
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = p.add_run(_clean_latex(str(val)))
                set_run_font(run, CFG["font_body"], CFG["size_caption"])



def add_formula(doc, formula_data):
    latex = str(formula_data.get("latex", formula_data.get("Formula", ""))).strip()
    number = str(formula_data.get("FormulaNumber", "")).strip()
    if not latex:
        return
    
    import re
    from lxml import etree
    from latex2mathml.converter import convert as latex2mathml
    from mathml2omml import convert as mathml2omml
    from docx.oxml.ns import qn
    
    try:
        # 1. Kalkulasi Lebar Kolom & Paksa Resize Skala Matriks
        col_w_cm = 7.5 if CFG.get("columns", 2) >= 2 else 16.0
        max_fw_cm = col_w_cm * 0.90
        
        cleaned = re.sub(r'\\[a-zA-Z]+|\{|\}|\[|\]|\^|\_|\$|\\', '', latex)
        formula_size = CFG["size_body"]
        
        is_matrix = "matrix" in latex or "cases" in latex or "\\\\" in latex
        if is_matrix:
            formula_size = max(5.0, formula_size - 2.5) 
        else:
            est_cm = len(cleaned) * formula_size * 0.38 / 28.35
            if est_cm > max_fw_cm:
                scale = max_fw_cm / est_cm
                formula_size = max(5.0, formula_size * scale)
                
        effective_halfpt = int(formula_size * 2)

        # 2. Konversi ke OMML sebagai Inline Math (BUKAN oMathPara)
        mathml_str = latex2mathml(latex)
        omml_str = mathml2omml(mathml_str)
        
        MATH_NS = "http://schemas.openxmlformats.org/officeDocument/2006/math"
        
        omml_inner = omml_str.replace(f'<m:oMath xmlns:m="{MATH_NS}">', '').replace('</m:oMath>', '')
        if omml_inner.startswith('<m:oMath>'):
            omml_inner = omml_inner.replace('<m:oMath>', '', 1)
            
        omml_wrapped = f'<m:oMath xmlns:m="{MATH_NS}">{omml_inner}</m:oMath>'
        oMath = etree.fromstring(omml_wrapped)
        
        # 3. Injeksi Properties OpenXML Legal (Harus di insert di INDEX 0)
        for omath_run in oMath.iter(f'{{{MATH_NS}}}r'):
            wrPr = omath_run.find(qn('w:rPr'))
            if wrPr is None:
                wrPr = etree.Element(qn('w:rPr'))
                omath_run.insert(0, wrPr)  # INI WAJIB INSERT(0), JANGAN SUBELEMENT
            
            rFonts = wrPr.find(qn('w:rFonts'))
            if rFonts is None:
                rFonts = etree.SubElement(wrPr, qn('w:rFonts'))
            rFonts.set(qn('w:ascii'), 'Cambria Math')
            rFonts.set(qn('w:hAnsi'), 'Cambria Math')
            
            sz = wrPr.find(qn('w:sz'))
            if sz is None:
                sz = etree.SubElement(wrPr, qn('w:sz'))
            sz.set(qn('w:val'), str(effective_halfpt))
            
            szCs = wrPr.find(qn('w:szCs'))
            if szCs is None:
                szCs = etree.SubElement(wrPr, qn('w:szCs'))
            szCs.set(qn('w:val'), str(effective_halfpt))

        # 4. Bangun Paragraf & Setup TABS (Agar bisa sejajar)
        body = doc._element.body
        final_sectpr = body.find(qn("w:sectPr"))
        
        p_elem = etree.Element(qn("w:p"))
        pPr = etree.SubElement(p_elem, qn("w:pPr"))
        
        jc = etree.SubElement(pPr, qn("w:jc"))
        jc.set(qn("w:val"), "left")
        
        spacing = etree.SubElement(pPr, qn("w:spacing"))
        spacing.set(qn("w:before"), "120")
        spacing.set(qn("w:after"), "120")
        spacing.set(qn("w:line"), "240")
        spacing.set(qn("w:lineRule"), "auto")
        
        center_twips = int((col_w_cm * 28.346 * 20) / 2)
        right_twips = int(col_w_cm * 28.346 * 20)
        
        tabs = etree.SubElement(pPr, qn("w:tabs"))
        tab_center = etree.SubElement(tabs, qn("w:tab"))
        tab_center.set(qn("w:val"), "center")
        tab_center.set(qn("w:pos"), str(center_twips))
        
        tab_right = etree.SubElement(tabs, qn("w:tab"))
        tab_right.set(qn("w:val"), "right")
        tab_right.set(qn("w:pos"), str(right_twips))

        # 5. Eksekusi Struktur Paragraf: [Tab Center] -> Formula -> [Tab Right] -> Number
        run_tab1 = etree.SubElement(p_elem, qn("w:r"))
        etree.SubElement(run_tab1, qn("w:tab"))
        
        p_elem.append(oMath)
        
        if number:
            run_num = etree.SubElement(p_elem, qn("w:r"))
            etree.SubElement(run_num, qn("w:tab"))
            
            rPr_num = etree.SubElement(run_num, qn("w:rPr"))
            rFonts_num = etree.SubElement(rPr_num, qn("w:rFonts"))
            rFonts_num.set(qn("w:ascii"), CFG["font_body"])
            
            sz_num = etree.SubElement(rPr_num, qn("w:sz"))
            sz_num.set(qn("w:val"), str(CFG["size_body"] * 2))
            
            t_num = etree.SubElement(run_num, qn("w:t"))
            t_num.text = f"({number})"
            t_num.set(qn("xml:space"), "preserve")
        
        # 6. Finalisasi Paragraf
        if final_sectpr is not None:
            final_sectpr.addprevious(p_elem)
        else:
            body.append(p_elem)
            
    except Exception as e:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_para_spacing(p, before_pt=6, after_pt=6)
        display = f"{latex}    ({number})" if number else latex
        run = p.add_run(display)
        set_run_font(run, CFG["font_body"], CFG["size_body"], bold=True, color=CFG["heading_color"])


def add_references(doc, data):
    refs_data = data.get("references", {})
    if isinstance(refs_data, dict):
        refs_list = refs_data.get("content") or refs_data.get("items") or []
    elif isinstance(refs_data, list):
        refs_list = refs_data
    else:
        refs_list = []

    if not refs_list:
        return

    # Heading
    add_section_heading(doc, "References")

    # Items
    for i, ref in enumerate(refs_list, 1):
        ref_text = _format_reference(ref)
        if not ref_text:
            continue
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        set_para_spacing(p, before_pt=0, after_pt=0)
        set_para_indent(p, left_tw=360, hanging_tw=360)
        run = p.add_run(f"[{i}] {ref_text}")
        set_run_font(run, CFG["font_body"], CFG["size_reference"])


def process_content_items(doc, content_list, fig_counter, tbl_counter):
    """Process a list of content items (text, gambar, rumus, tabel)."""
    if not isinstance(content_list, list):
        return fig_counter, tbl_counter

    for item in content_list:
        if not isinstance(item, dict):
            continue
        kind = str(item.get("id", "")).lower()

        if kind in ("text", "paragraf", "paragraph"):
            text = str(item.get("text", item.get("Text", ""))).strip()
            if text:
                add_body_text(doc, text)

        elif kind in ("gambar", "image", "figure"):
            fig_counter += 1
            add_figure(doc, item, fig_counter)

        elif kind in ("tabel", "table"):
            tbl_counter += 1
            add_table_element(doc, item, tbl_counter)

        elif kind in ("rumus", "equation", "formula", "persamaan"):
            add_formula(doc, item)

    return fig_counter, tbl_counter


def process_section(doc, section_data, fig_counter, tbl_counter):
    """Process a section (and its subsections) recursively."""
    if not isinstance(section_data, dict):
        return fig_counter, tbl_counter

    # Section title
    title = str(section_data.get("title", section_data.get("Title", ""))).strip()
    if title:
        add_section_heading(doc, title)

    # Content items at this level
    content = section_data.get("content", section_data.get("Content", []))
    fig_counter, tbl_counter = process_content_items(doc, content, fig_counter, tbl_counter)

    # Find subsections (keys like section2a, section2b, etc.)
    for key in sorted(section_data.keys()):
        if key in ("title", "Title", "content", "Content", "id"):
            continue
        val = section_data[key]
        if isinstance(val, dict) and ("title" in val or "Title" in val or "content" in val or "Content" in val):
            # This is a subsection
            sub_title = str(val.get("title", val.get("Title", ""))).strip()
            if sub_title:
                add_subsection_heading(doc, sub_title)
            sub_content = val.get("content", val.get("Content", []))
            fig_counter, tbl_counter = process_content_items(doc, sub_content, fig_counter, tbl_counter)

            # Check for sub-subsections
            for subkey in sorted(val.keys()):
                if subkey in ("title", "Title", "content", "Content", "id"):
                    continue
                subval = val[subkey]
                if isinstance(subval, dict) and ("title" in subval or "Title" in subval or "content" in subval or "Content" in subval):
                    ssub_title = str(subval.get("title", subval.get("Title", ""))).strip()
                    if ssub_title:
                        add_subsection_heading(doc, ssub_title)
                    ssub_content = subval.get("content", subval.get("Content", []))
                    fig_counter, tbl_counter = process_content_items(doc, ssub_content, fig_counter, tbl_counter)

    return fig_counter, tbl_counter



def generate():
    data = load_json()

    shutil.copy2(str(TEMPLATE_DOCX), str(OUTPUT_DOCX))
    doc = Document(str(OUTPUT_DOCX))

    # Clear body but keep section break paragraphs in place
    sectpr_paras = clear_body(doc)
    body = doc._element.body

    # Find insertion point: before first sectPr paragraph (or final sectPr)
    if sectpr_paras:
        insert_before = sectpr_paras[0]
    else:
        insert_before = body.find(qn("w:sectPr"))

    # Generate title block
    add_title(doc, data)
    add_authors(doc, data)
    add_abstract(doc, data)
    add_keywords(doc, data)

    # Move title block paragraphs to before first section break
    if insert_before is not None:
        new_paras = []
        for child in list(body):
            if child.tag == qn("w:sectPr"):
                continue
            if child.tag == qn("w:p"):
                pPr = child.find(qn("w:pPr"))
                if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                    continue
            if list(body).index(child) > list(body).index(insert_before):
                new_paras.append(child)
        for p in new_paras:
            body.remove(p)
            body.insert(list(body).index(insert_before), p)

    # Determine where body content goes
    if sectpr_paras:
        body_insert_before = sectpr_paras[-1]
    else:
        body_insert_before = body.find(qn("w:sectPr"))

    # Generate body content
    fig_counter = 0
    tbl_counter = 0
    for i in range(1, 30):
        key = f"section{i}"
        if key in data:
            fig_counter, tbl_counter = process_section(doc, data[key], fig_counter, tbl_counter)

    # References
    add_references(doc, data)

    # Move body content to before the target insertion point
    if body_insert_before is not None and sectpr_paras:
        new_elements = []
        for child in list(body):
            if child.tag == qn("w:sectPr"):
                continue
            if child.tag == qn("w:p"):
                pPr = child.find(qn("w:pPr"))
                if pPr is not None and pPr.find(qn("w:sectPr")) is not None:
                    continue
            try:
                if list(body).index(child) >= list(body).index(body_insert_before):
                    if child != body_insert_before:
                        new_elements.append(child)
            except ValueError:
                pass
        for el in new_elements:
            body.remove(el)
            body.insert(list(body).index(body_insert_before), el)

    # Remove trailing empty sectPr paragraphs (fixes blank pages)
    remove_trailing_empty_sectpr_paras(doc)

    # Save
    doc.save(str(OUTPUT_DOCX))
    print(f"Generated: {OUTPUT_DOCX}")
    print("[VERIFY] OK")
    return str(OUTPUT_DOCX)



def build_pdf(json_path: Path, pdf_path: Path, template_path=None) -> Path:
    """Build a PDF for this journal template from a paper JSON.

    Writes a temporary .docx via generate(), then converts to .pdf
    via LibreOffice headless.  Final PDF is written to ``pdf_path``.
    """
    import sys as _sys
    import tempfile as _tf

    _json_path = Path(json_path)
    _pdf_path = Path(pdf_path)
    _pdf_path.parent.mkdir(parents=True, exist_ok=True)

    # Create temp docx path
    with _tf.NamedTemporaryFile(suffix=".docx", delete=False) as _tmp:
        _tmp_docx = Path(_tmp.name)

    _mod = _sys.modules[__name__]
    _saved_in = getattr(_mod, "TEMPLATE_JSON", None)
    _saved_out = getattr(_mod, "OUTPUT_DOCX", None)

    try:
        setattr(_mod, "TEMPLATE_JSON", _json_path)
        setattr(_mod, "OUTPUT_DOCX", _tmp_docx)
        generate()
    finally:
        if _saved_in is not None:
            setattr(_mod, "TEMPLATE_JSON", _saved_in)
        if _saved_out is not None:
            setattr(_mod, "OUTPUT_DOCX", _saved_out)

    try:
        from ._render_pdf import convert_docx_to_pdf
        return convert_docx_to_pdf(_tmp_docx, _pdf_path)
    finally:
        _tmp_docx.unlink(missing_ok=True)

if __name__ == "__main__":
    generate()
