"""
PDF Exporter
============
Exports papers to PDF format.

Supports two methods:
1. Convert DOCX to PDF (requires LibreOffice or docx2pdf)
2. Direct PDF generation using ReportLab (basic formatting)
"""

import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Optional

from .base import BaseExporter, ExportError
from .docx_exporter import DOCXExporter


class PDFExporter(BaseExporter):
    """
    PDF exporter with multiple generation strategies.
    
    Priority:
    1. Convert DOCX to PDF using LibreOffice (best quality)
    2. Convert DOCX to PDF using docx2pdf (Windows)
    3. Direct PDF generation using ReportLab (basic)
    """
    
    def __init__(self, template: Optional[str] = None):
        """
        Initialize PDF exporter.
        
        Args:
            template: Template name for DOCX generation
        """
        super().__init__(template)
        self.docx_exporter = DOCXExporter(template)
        
    def check_libreoffice(self) -> Optional[str]:
        """
        Check if LibreOffice is available.
        
        Returns:
            Path to LibreOffice executable or None
        """
        commands = [
            'libreoffice',
            'soffice',
            '/usr/bin/libreoffice',
            '/usr/bin/soffice',
            'C:\\Program Files\\LibreOffice\\program\\soffice.exe',
        ]
        
        for cmd in commands:
            try:
                result = subprocess.run(
                    [cmd, '--version'],
                    capture_output=True,
                    timeout=5
                )
                if result.returncode == 0:
                    return cmd
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
        
        return None
    
    def convert_docx_to_pdf_libreoffice(
        self,
        docx_path: Path,
        output_path: Path
    ) -> Path:
        """
        Convert DOCX to PDF using LibreOffice.
        
        Args:
            docx_path: Path to DOCX file
            output_path: Desired PDF output path
            
        Returns:
            Path to generated PDF
            
        Raises:
            ExportError: If conversion fails
        """
        libreoffice = self.check_libreoffice()
        if not libreoffice:
            raise ExportError("LibreOffice not found")
        
        try:
            # LibreOffice converts to output directory with same basename
            output_dir = output_path.parent
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Run LibreOffice conversion
            result = subprocess.run(
                [
                    libreoffice,
                    '--headless',
                    '--convert-to', 'pdf',
                    '--outdir', str(output_dir),
                    str(docx_path)
                ],
                capture_output=True,
                timeout=60,
                text=True
            )
            
            if result.returncode != 0:
                raise ExportError(f"LibreOffice conversion failed: {result.stderr}")
            
            # LibreOffice creates PDF with same name as DOCX
            generated_pdf = output_dir / f"{docx_path.stem}.pdf"
            
            if not generated_pdf.exists():
                raise ExportError("PDF not generated by LibreOffice")
            
            # Rename to desired output path if different
            if generated_pdf != output_path:
                generated_pdf.rename(output_path)
            
            return output_path
            
        except subprocess.TimeoutExpired:
            raise ExportError("LibreOffice conversion timed out")
        except Exception as e:
            raise ExportError(f"LibreOffice conversion failed: {e}")
    
    def convert_docx_to_pdf_docx2pdf(
        self,
        docx_path: Path,
        output_path: Path
    ) -> Path:
        """
        Convert DOCX to PDF using docx2pdf library (Windows).
        
        Args:
            docx_path: Path to DOCX file
            output_path: Desired PDF output path
            
        Returns:
            Path to generated PDF
            
        Raises:
            ExportError: If conversion fails
        """
        try:
            from docx2pdf import convert
            
            output_path.parent.mkdir(parents=True, exist_ok=True)
            convert(str(docx_path), str(output_path))
            
            if not output_path.exists():
                raise ExportError("PDF not generated by docx2pdf")
            
            return output_path
            
        except ImportError:
            raise ExportError("docx2pdf library not available")
        except Exception as e:
            raise ExportError(f"docx2pdf conversion failed: {e}")
    
    def generate_pdf_reportlab(
        self,
        paper_data: Dict[str, Any],
        output_path: Path
    ) -> Path:
        """
        Generate PDF directly using ReportLab (basic formatting).
        
        Args:
            paper_data: Paper data dictionary
            output_path: Desired PDF output path
            
        Returns:
            Path to generated PDF
            
        Raises:
            ExportError: If generation fails
        """
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
            
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Create PDF document
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18,
            )
            
            # Container for PDF elements
            story = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=16,
                textColor='black',
                spaceAfter=30,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold'
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=12,
                textColor='black',
                spaceAfter=12,
                fontName='Helvetica-Bold'
            )
            
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['BodyText'],
                fontSize=10,
                alignment=TA_JUSTIFY,
                spaceAfter=12,
            )
            
            # Add title
            title = paper_data.get('title', 'Untitled Paper')
            story.append(Paragraph(title, title_style))
            story.append(Spacer(1, 0.2*inch))
            
            # Add authors
            authors = paper_data.get('authors', [])
            if authors:
                author_text = ', '.join([
                    a.get('name', '') for a in authors if isinstance(a, dict) and a.get('name')
                ])
                if author_text:
                    story.append(Paragraph(author_text, styles['Normal']))
                    story.append(Spacer(1, 0.2*inch))
            
            # Add abstract
            abstract = paper_data.get('abstract', '')
            if abstract:
                story.append(Paragraph('<b>Abstract</b>', heading_style))
                story.append(Paragraph(abstract, body_style))
                story.append(Spacer(1, 0.2*inch))
            
            # Add keywords
            keywords = paper_data.get('keywords', [])
            if keywords:
                kw_text = ', '.join(keywords) if isinstance(keywords, list) else str(keywords)
                story.append(Paragraph(f'<b>Keywords:</b> {kw_text}', body_style))
                story.append(Spacer(1, 0.3*inch))
            
            # Add sections
            sections = self.get_sections(paper_data)
            for section in sections:
                section_title = section.get('title', '')
                section_content = section.get('content', '')
                
                if section_title:
                    story.append(Paragraph(section_title, heading_style))
                
                if section_content:
                    # Split content into paragraphs
                    paragraphs = section_content.split('\n\n')
                    for para in paragraphs:
                        if para.strip():
                            story.append(Paragraph(para.strip(), body_style))
                
                story.append(Spacer(1, 0.2*inch))
            
            # Add references
            references = self.get_references(paper_data)
            if references:
                story.append(Paragraph('<b>References</b>', heading_style))
                for i, ref in enumerate(references, 1):
                    if isinstance(ref, dict):
                        ref_text = self._format_reference(ref, i)
                    else:
                        ref_text = f"[{i}] {ref}"
                    story.append(Paragraph(ref_text, body_style))
            
            # Build PDF
            doc.build(story)
            
            return output_path
            
        except ImportError:
            raise ExportError("ReportLab library not available")
        except Exception as e:
            raise ExportError(f"ReportLab PDF generation failed: {e}")
    
    def _format_reference(self, ref: Dict[str, Any], index: int) -> str:
        """Format a reference for PDF output."""
        parts = [f"[{index}]"]
        
        if ref.get('authors'):
            parts.append(ref['authors'])
        if ref.get('title'):
            parts.append(f'"{ref["title"]}"')
        if ref.get('venue'):
            parts.append(ref['venue'])
        if ref.get('year'):
            parts.append(f"({ref['year']})")
        
        return ' '.join(parts)
    
    def export(
        self,
        paper_data: Dict[str, Any],
        output_path: Path,
        **kwargs
    ) -> Path:
        """
        Export paper to PDF format.
        
        Args:
            paper_data: Paper data dictionary
            output_path: Path where PDF should be saved
            **kwargs: Additional options:
                - method: 'libreoffice', 'docx2pdf', or 'reportlab'
                - keep_docx: Keep intermediate DOCX file (default: False)
                
        Returns:
            Path to exported PDF file
            
        Raises:
            ExportError: If export fails
        """
        if not self.validate_paper_data(paper_data):
            raise ExportError("Invalid paper data: missing required fields")
        
        method = kwargs.get('method', 'auto')
        keep_docx = kwargs.get('keep_docx', False)
        
        # Try methods in order
        if method == 'auto':
            methods = ['libreoffice', 'docx2pdf', 'reportlab']
        else:
            methods = [method]
        
        last_error = None
        
        for m in methods:
            try:
                if m == 'reportlab':
                    return self.generate_pdf_reportlab(paper_data, output_path)
                
                # For DOCX-based methods, generate DOCX first
                docx_path = output_path.with_suffix('.docx')
                self.docx_exporter.export(paper_data, docx_path)
                
                try:
                    if m == 'libreoffice':
                        result = self.convert_docx_to_pdf_libreoffice(docx_path, output_path)
                    elif m == 'docx2pdf':
                        result = self.convert_docx_to_pdf_docx2pdf(docx_path, output_path)
                    else:
                        continue
                    
                    # Cleanup DOCX if not keeping
                    if not keep_docx and docx_path.exists():
                        docx_path.unlink()
                    
                    return result
                    
                except ExportError as e:
                    # Cleanup DOCX on failure
                    if docx_path.exists():
                        docx_path.unlink()
                    raise e
                    
            except ExportError as e:
                last_error = e
                continue
        
        # All methods failed
        raise ExportError(
            f"All PDF export methods failed. Last error: {last_error}"
        )
